// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for HealthResponseStatus.
const (
	Ok          HealthResponseStatus = "ok"
	Unavailable HealthResponseStatus = "unavailable"
)

// Valid indicates whether the value is a known member of the HealthResponseStatus enum.
func (e HealthResponseStatus) Valid() bool {
	switch e {
	case Ok:
		return true
	case Unavailable:
		return true
	default:
		return false
	}
}

// Defines values for LoginRequestClientType.
const (
	LoginRequestClientTypeNative LoginRequestClientType = "native"
	LoginRequestClientTypeWeb    LoginRequestClientType = "web"
)

// Valid indicates whether the value is a known member of the LoginRequestClientType enum.
func (e LoginRequestClientType) Valid() bool {
	switch e {
	case LoginRequestClientTypeNative:
		return true
	case LoginRequestClientTypeWeb:
		return true
	default:
		return false
	}
}

// Defines values for LoginResponseTokenType.
const (
	Bearer LoginResponseTokenType = "Bearer"
)

// Valid indicates whether the value is a known member of the LoginResponseTokenType enum.
func (e LoginResponseTokenType) Valid() bool {
	switch e {
	case Bearer:
		return true
	default:
		return false
	}
}

// Defines values for RefreshRequestClientType.
const (
	RefreshRequestClientTypeNative RefreshRequestClientType = "native"
	RefreshRequestClientTypeWeb    RefreshRequestClientType = "web"
)

// Valid indicates whether the value is a known member of the RefreshRequestClientType enum.
func (e RefreshRequestClientType) Valid() bool {
	switch e {
	case RefreshRequestClientTypeNative:
		return true
	case RefreshRequestClientTypeWeb:
		return true
	default:
		return false
	}
}

// Defines values for UserCurrency.
const (
	IDR UserCurrency = "IDR"
)

// Valid indicates whether the value is a known member of the UserCurrency enum.
func (e UserCurrency) Valid() bool {
	switch e {
	case IDR:
		return true
	default:
		return false
	}
}

// Defines values for UserRole.
const (
	UserRoleAdmin UserRole = "admin"
	UserRoleUser  UserRole = "user"
)

// Valid indicates whether the value is a known member of the UserRole enum.
func (e UserRole) Valid() bool {
	switch e {
	case UserRoleAdmin:
		return true
	case UserRoleUser:
		return true
	default:
		return false
	}
}

// Error defines model for Error.
type Error struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error Error `json:"error"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	Status HealthResponseStatus `json:"status"`
}

// HealthResponseStatus defines model for HealthResponse.Status.
type HealthResponseStatus string

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	// ClientType Use `native` for Android and iOS clients.
	ClientType LoginRequestClientType `json:"client_type"`
	Email      openapi_types.Email    `json:"email"`
	Password   string                 `json:"password"`
}

// LoginRequestClientType Use `native` for Android and iOS clients.
type LoginRequestClientType string

// LoginResponse defines model for LoginResponse.
type LoginResponse struct {
	AccessToken string `json:"access_token"`

	// ExpiresIn Example: 86400
	ExpiresIn int64 `json:"expires_in"`

	// RefreshToken Returned only for native clients.
	RefreshToken *string                `json:"refresh_token,omitempty"`
	TokenType    LoginResponseTokenType `json:"token_type"`
}

// LoginResponseTokenType defines model for LoginResponse.TokenType.
type LoginResponseTokenType string

// ProfileRequest defines model for ProfileRequest.
type ProfileRequest struct {
	// Timezone Example: Asia/Jakarta
	Timezone string `json:"timezone"`
	Version  int32  `json:"version"`
}

// RefreshRequest defines model for RefreshRequest.
type RefreshRequest struct {
	ClientType RefreshRequestClientType `json:"client_type"`

	// RefreshToken Required only for native clients; browser clients use an HttpOnly cookie.
	RefreshToken *string `json:"refresh_token,omitempty"`
}

// RefreshRequestClientType defines model for RefreshRequest.ClientType.
type RefreshRequestClientType string

// RegisterRequest defines model for RegisterRequest.
type RegisterRequest struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`

	// Timezone Example: Asia/Jakarta
	Timezone string `json:"timezone"`
}

// User defines model for User.
type User struct {
	Currency UserCurrency        `json:"currency"`
	Email    openapi_types.Email `json:"email"`
	Id       openapi_types.UUID  `json:"id"`
	IsDelete bool                `json:"isDelete"`
	Role     UserRole            `json:"role"`
	Timezone string              `json:"timezone"`
	Version  int32               `json:"version"`
}

// UserCurrency defines model for User.Currency.
type UserCurrency string

// UserRole defines model for User.Role.
type UserRole string

// UserResponse defines model for UserResponse.
type UserResponse struct {
	Data User `json:"data"`
}

// AuthenticationFailed defines model for AuthenticationFailed.
type AuthenticationFailed = ErrorResponse

// Conflict defines model for Conflict.
type Conflict = ErrorResponse

// Forbidden defines model for Forbidden.
type Forbidden = ErrorResponse

// InternalError defines model for InternalError.
type InternalError = ErrorResponse

// RateLimited defines model for RateLimited.
type RateLimited = ErrorResponse

// ServiceUnavailable defines model for ServiceUnavailable.
type ServiceUnavailable = HealthResponse

// ValidationError defines model for ValidationError.
type ValidationError = ErrorResponse

// DeleteMeParams defines parameters for DeleteMe.
type DeleteMeParams struct {
	// IfMatch Current profile version, for example `"3"`.
	IfMatch string `json:"If-Match"`
}

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = LoginRequest

// LogoutJSONRequestBody defines body for Logout for application/json ContentType.
type LogoutJSONRequestBody = RefreshRequest

// RefreshJSONRequestBody defines body for Refresh for application/json ContentType.
type RefreshJSONRequestBody = RefreshRequest

// RegisterJSONRequestBody defines body for Register for application/json ContentType.
type RegisterJSONRequestBody = RegisterRequest

// UpdateMeJSONRequestBody defines body for UpdateMe for application/json ContentType.
type UpdateMeJSONRequestBody = ProfileRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Login Create an access and refresh session
	// (POST /api/v1/auth/login)
	Login(ctx *echo.Context) error
	// Logout Revoke the refresh-token family
	// (POST /api/v1/auth/logout)
	Logout(ctx *echo.Context) error
	// Refresh Rotate a refresh session
	// (POST /api/v1/auth/refresh)
	Refresh(ctx *echo.Context) error
	// Register Register a standard user
	// (POST /api/v1/auth/register)
	Register(ctx *echo.Context) error
	// DeleteMe Soft-delete the current account
	// (DELETE /api/v1/me)
	DeleteMe(ctx *echo.Context, params DeleteMeParams) error
	// GetMe Get the current profile
	// (GET /api/v1/me)
	GetMe(ctx *echo.Context) error
	// UpdateMe Update the current profile timezone
	// (PATCH /api/v1/me)
	UpdateMe(ctx *echo.Context) error
	// HealthLive Process liveness
	// (GET /health/live)
	HealthLive(ctx *echo.Context) error
	// HealthReady Dependency readiness
	// (GET /health/ready)
	HealthReady(ctx *echo.Context) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// Login converts echo context to params.
func (w *ServerInterfaceWrapper) Login(ctx *echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.Login(ctx)
	return err
}

// Logout converts echo context to params.
func (w *ServerInterfaceWrapper) Logout(ctx *echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.Logout(ctx)
	return err
}

// Refresh converts echo context to params.
func (w *ServerInterfaceWrapper) Refresh(ctx *echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.Refresh(ctx)
	return err
}

// Register converts echo context to params.
func (w *ServerInterfaceWrapper) Register(ctx *echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.Register(ctx)
	return err
}

// DeleteMe converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteMe(ctx *echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params DeleteMeParams

	headers := ctx.Request().Header
	// ------------- Required header parameter "If-Match" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("If-Match")]; found {
		var IfMatch string
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for If-Match, got %d", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "If-Match", valueList[0], &IfMatch, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter If-Match: %s", err))
		}

		params.IfMatch = IfMatch
	} else {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Header parameter If-Match is required, but not found"))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteMe(ctx, params)
	return err
}

// GetMe converts echo context to params.
func (w *ServerInterfaceWrapper) GetMe(ctx *echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetMe(ctx)
	return err
}

// UpdateMe converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateMe(ctx *echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UpdateMe(ctx)
	return err
}

// HealthLive converts echo context to params.
func (w *ServerInterfaceWrapper) HealthLive(ctx *echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.HealthLive(ctx)
	return err
}

// HealthReady converts echo context to params.
func (w *ServerInterfaceWrapper) HealthReady(ctx *echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.HealthReady(ctx)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
}

// RegisterHandlersOptions configures RegisterHandlersWithOptions.
type RegisterHandlersOptions struct {
	// BaseURL is prepended to every registered path so the API can be served
	// under a prefix.
	BaseURL string
	// OperationMiddlewares lets the caller attach per-operation middleware at
	// registration time. The map key is the OpenAPI `operationId` value as it
	// appears in the spec (the raw, un-normalized form). Operations that have
	// no entry are registered with no extra middleware. A nil map disables
	// per-operation middleware entirely.
	OperationMiddlewares map[string][]echo.MiddlewareFunc
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{})
}

// RegisterHandlersWithBaseURL registers handlers and prepends BaseURL to the
// paths so the API can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{BaseURL: baseURL})
}

// RegisterHandlersWithOptions registers handlers using the supplied options,
// including any per-operation middleware.
func RegisterHandlersWithOptions(router EchoRouter, si ServerInterface, options RegisterHandlersOptions) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(options.BaseURL+"/health/live", wrapper.HealthLive, options.OperationMiddlewares["healthLive"]...)
	router.GET(options.BaseURL+"/health/ready", wrapper.HealthReady, options.OperationMiddlewares["healthReady"]...)
	router.POST(options.BaseURL+"/api/v1/auth/register", wrapper.Register, options.OperationMiddlewares["register"]...)
	router.POST(options.BaseURL+"/api/v1/auth/login", wrapper.Login, options.OperationMiddlewares["login"]...)
	router.POST(options.BaseURL+"/api/v1/auth/refresh", wrapper.Refresh, options.OperationMiddlewares["refresh"]...)
	router.POST(options.BaseURL+"/api/v1/auth/logout", wrapper.Logout, options.OperationMiddlewares["logout"]...)
	router.DELETE(options.BaseURL+"/api/v1/me", wrapper.DeleteMe, options.OperationMiddlewares["deleteMe"]...)
	router.GET(options.BaseURL+"/api/v1/me", wrapper.GetMe, options.OperationMiddlewares["getMe"]...)
	router.PATCH(options.BaseURL+"/api/v1/me", wrapper.UpdateMe, options.OperationMiddlewares["updateMe"]...)

}

type AuthenticationFailedJSONResponse ErrorResponse

type ConflictJSONResponse ErrorResponse

type ForbiddenJSONResponse ErrorResponse

type InternalErrorJSONResponse ErrorResponse

type RateLimitedResponseHeaders struct {
	RetryAfter int
}
type RateLimitedJSONResponse struct {
	Body ErrorResponse

	Headers RateLimitedResponseHeaders
}

type ServiceUnavailableJSONResponse HealthResponse

type ValidationErrorJSONResponse ErrorResponse

type LoginRequestObject struct {
	Body *LoginJSONRequestBody
}

type LoginResponseObject interface {
	VisitLoginResponse(w http.ResponseWriter) error
}

type Login200JSONResponse LoginResponse

func (response Login200JSONResponse) VisitLoginResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type Login401JSONResponse struct {
	AuthenticationFailedJSONResponse
}

func (response Login401JSONResponse) VisitLoginResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type Login403JSONResponse struct{ ForbiddenJSONResponse }

func (response Login403JSONResponse) VisitLoginResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type Login422JSONResponse struct{ ValidationErrorJSONResponse }

func (response Login422JSONResponse) VisitLoginResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)
	_, err := buf.WriteTo(w)
	return err
}

type Login429JSONResponse struct{ RateLimitedJSONResponse }

func (response Login429JSONResponse) VisitLoginResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("Retry-After", fmt.Sprint(response.Headers.RetryAfter))
	w.WriteHeader(429)
	_, err := buf.WriteTo(w)
	return err
}

type LogoutRequestObject struct {
	Body *LogoutJSONRequestBody
}

type LogoutResponseObject interface {
	VisitLogoutResponse(w http.ResponseWriter) error
}

type Logout204Response struct {
}

func (response Logout204Response) VisitLogoutResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type Logout403JSONResponse struct{ ForbiddenJSONResponse }

func (response Logout403JSONResponse) VisitLogoutResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type Logout422JSONResponse struct{ ValidationErrorJSONResponse }

func (response Logout422JSONResponse) VisitLogoutResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)
	_, err := buf.WriteTo(w)
	return err
}

type RefreshRequestObject struct {
	Body *RefreshJSONRequestBody
}

type RefreshResponseObject interface {
	VisitRefreshResponse(w http.ResponseWriter) error
}

type Refresh200JSONResponse LoginResponse

func (response Refresh200JSONResponse) VisitRefreshResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type Refresh401JSONResponse struct {
	AuthenticationFailedJSONResponse
}

func (response Refresh401JSONResponse) VisitRefreshResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type Refresh403JSONResponse struct{ ForbiddenJSONResponse }

func (response Refresh403JSONResponse) VisitRefreshResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type Refresh422JSONResponse struct{ ValidationErrorJSONResponse }

func (response Refresh422JSONResponse) VisitRefreshResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)
	_, err := buf.WriteTo(w)
	return err
}

type RegisterRequestObject struct {
	Body *RegisterJSONRequestBody
}

type RegisterResponseObject interface {
	VisitRegisterResponse(w http.ResponseWriter) error
}

type Register201JSONResponse UserResponse

func (response Register201JSONResponse) VisitRegisterResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type Register409JSONResponse struct{ ConflictJSONResponse }

func (response Register409JSONResponse) VisitRegisterResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type Register422JSONResponse struct{ ValidationErrorJSONResponse }

func (response Register422JSONResponse) VisitRegisterResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)
	_, err := buf.WriteTo(w)
	return err
}

type Register500JSONResponse struct{ InternalErrorJSONResponse }

func (response Register500JSONResponse) VisitRegisterResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteMeRequestObject struct {
	Params DeleteMeParams
}

type DeleteMeResponseObject interface {
	VisitDeleteMeResponse(w http.ResponseWriter) error
}

type DeleteMe204Response struct {
}

func (response DeleteMe204Response) VisitDeleteMeResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteMe401JSONResponse struct {
	AuthenticationFailedJSONResponse
}

func (response DeleteMe401JSONResponse) VisitDeleteMeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteMe409JSONResponse struct{ ConflictJSONResponse }

func (response DeleteMe409JSONResponse) VisitDeleteMeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteMe422JSONResponse struct{ ValidationErrorJSONResponse }

func (response DeleteMe422JSONResponse) VisitDeleteMeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)
	_, err := buf.WriteTo(w)
	return err
}

type GetMeRequestObject struct {
}

type GetMeResponseObject interface {
	VisitGetMeResponse(w http.ResponseWriter) error
}

type GetMe200JSONResponse UserResponse

func (response GetMe200JSONResponse) VisitGetMeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetMe401JSONResponse struct {
	AuthenticationFailedJSONResponse
}

func (response GetMe401JSONResponse) VisitGetMeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateMeRequestObject struct {
	Body *UpdateMeJSONRequestBody
}

type UpdateMeResponseObject interface {
	VisitUpdateMeResponse(w http.ResponseWriter) error
}

type UpdateMe200JSONResponse UserResponse

func (response UpdateMe200JSONResponse) VisitUpdateMeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateMe401JSONResponse struct {
	AuthenticationFailedJSONResponse
}

func (response UpdateMe401JSONResponse) VisitUpdateMeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateMe409JSONResponse struct{ ConflictJSONResponse }

func (response UpdateMe409JSONResponse) VisitUpdateMeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateMe422JSONResponse struct{ ValidationErrorJSONResponse }

func (response UpdateMe422JSONResponse) VisitUpdateMeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)
	_, err := buf.WriteTo(w)
	return err
}

type HealthLiveRequestObject struct {
}

type HealthLiveResponseObject interface {
	VisitHealthLiveResponse(w http.ResponseWriter) error
}

type HealthLive200JSONResponse HealthResponse

func (response HealthLive200JSONResponse) VisitHealthLiveResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type HealthLive503JSONResponse struct{ ServiceUnavailableJSONResponse }

func (response HealthLive503JSONResponse) VisitHealthLiveResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type HealthReadyRequestObject struct {
}

type HealthReadyResponseObject interface {
	VisitHealthReadyResponse(w http.ResponseWriter) error
}

type HealthReady200JSONResponse HealthResponse

func (response HealthReady200JSONResponse) VisitHealthReadyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type HealthReady503JSONResponse struct{ ServiceUnavailableJSONResponse }

func (response HealthReady503JSONResponse) VisitHealthReadyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Login Create an access and refresh session
	// (POST /api/v1/auth/login)
	Login(ctx context.Context, request LoginRequestObject) (LoginResponseObject, error)
	// Logout Revoke the refresh-token family
	// (POST /api/v1/auth/logout)
	Logout(ctx context.Context, request LogoutRequestObject) (LogoutResponseObject, error)
	// Refresh Rotate a refresh session
	// (POST /api/v1/auth/refresh)
	Refresh(ctx context.Context, request RefreshRequestObject) (RefreshResponseObject, error)
	// Register Register a standard user
	// (POST /api/v1/auth/register)
	Register(ctx context.Context, request RegisterRequestObject) (RegisterResponseObject, error)
	// DeleteMe Soft-delete the current account
	// (DELETE /api/v1/me)
	DeleteMe(ctx context.Context, request DeleteMeRequestObject) (DeleteMeResponseObject, error)
	// GetMe Get the current profile
	// (GET /api/v1/me)
	GetMe(ctx context.Context, request GetMeRequestObject) (GetMeResponseObject, error)
	// UpdateMe Update the current profile timezone
	// (PATCH /api/v1/me)
	UpdateMe(ctx context.Context, request UpdateMeRequestObject) (UpdateMeResponseObject, error)
	// HealthLive Process liveness
	// (GET /health/live)
	HealthLive(ctx context.Context, request HealthLiveRequestObject) (HealthLiveResponseObject, error)
	// HealthReady Dependency readiness
	// (GET /health/ready)
	HealthReady(ctx context.Context, request HealthReadyRequestObject) (HealthReadyResponseObject, error)
}

type StrictHandlerFunc func(ctx *echo.Context, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// Login operation middleware
func (sh *strictHandler) Login(ctx *echo.Context) error {
	var request LoginRequestObject

	var body LoginJSONRequestBody
	var err error
	if _, ok := ctx.Echo().Binder.(*echo.DefaultBinder); ok {
		// Bind only the request body, so that path and query parameters
		// are not also bound into the body struct.
		err = echo.BindBody(ctx, &body)
	} else {
		// A custom binder is installed on the Echo instance; defer to it
		// entirely, since echo.Binder does not expose body-only binding.
		err = ctx.Bind(&body)
	}
	if err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx *echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.Login(ctx.Request().Context(), request.(LoginRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Login")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(LoginResponseObject); ok {
		return validResponse.VisitLoginResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// Logout operation middleware
func (sh *strictHandler) Logout(ctx *echo.Context) error {
	var request LogoutRequestObject

	var body LogoutJSONRequestBody
	var err error
	if _, ok := ctx.Echo().Binder.(*echo.DefaultBinder); ok {
		// Bind only the request body, so that path and query parameters
		// are not also bound into the body struct.
		err = echo.BindBody(ctx, &body)
	} else {
		// A custom binder is installed on the Echo instance; defer to it
		// entirely, since echo.Binder does not expose body-only binding.
		err = ctx.Bind(&body)
	}
	if err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx *echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.Logout(ctx.Request().Context(), request.(LogoutRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Logout")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(LogoutResponseObject); ok {
		return validResponse.VisitLogoutResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// Refresh operation middleware
func (sh *strictHandler) Refresh(ctx *echo.Context) error {
	var request RefreshRequestObject

	var body RefreshJSONRequestBody
	var err error
	if _, ok := ctx.Echo().Binder.(*echo.DefaultBinder); ok {
		// Bind only the request body, so that path and query parameters
		// are not also bound into the body struct.
		err = echo.BindBody(ctx, &body)
	} else {
		// A custom binder is installed on the Echo instance; defer to it
		// entirely, since echo.Binder does not expose body-only binding.
		err = ctx.Bind(&body)
	}
	if err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx *echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.Refresh(ctx.Request().Context(), request.(RefreshRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Refresh")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(RefreshResponseObject); ok {
		return validResponse.VisitRefreshResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// Register operation middleware
func (sh *strictHandler) Register(ctx *echo.Context) error {
	var request RegisterRequestObject

	var body RegisterJSONRequestBody
	var err error
	if _, ok := ctx.Echo().Binder.(*echo.DefaultBinder); ok {
		// Bind only the request body, so that path and query parameters
		// are not also bound into the body struct.
		err = echo.BindBody(ctx, &body)
	} else {
		// A custom binder is installed on the Echo instance; defer to it
		// entirely, since echo.Binder does not expose body-only binding.
		err = ctx.Bind(&body)
	}
	if err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx *echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.Register(ctx.Request().Context(), request.(RegisterRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Register")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(RegisterResponseObject); ok {
		return validResponse.VisitRegisterResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// DeleteMe operation middleware
func (sh *strictHandler) DeleteMe(ctx *echo.Context, params DeleteMeParams) error {
	var request DeleteMeRequestObject

	request.Params = params

	handler := func(ctx *echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteMe(ctx.Request().Context(), request.(DeleteMeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteMe")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(DeleteMeResponseObject); ok {
		return validResponse.VisitDeleteMeResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetMe operation middleware
func (sh *strictHandler) GetMe(ctx *echo.Context) error {
	var request GetMeRequestObject

	handler := func(ctx *echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetMe(ctx.Request().Context(), request.(GetMeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetMe")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetMeResponseObject); ok {
		return validResponse.VisitGetMeResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// UpdateMe operation middleware
func (sh *strictHandler) UpdateMe(ctx *echo.Context) error {
	var request UpdateMeRequestObject

	var body UpdateMeJSONRequestBody
	var err error
	if _, ok := ctx.Echo().Binder.(*echo.DefaultBinder); ok {
		// Bind only the request body, so that path and query parameters
		// are not also bound into the body struct.
		err = echo.BindBody(ctx, &body)
	} else {
		// A custom binder is installed on the Echo instance; defer to it
		// entirely, since echo.Binder does not expose body-only binding.
		err = ctx.Bind(&body)
	}
	if err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx *echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateMe(ctx.Request().Context(), request.(UpdateMeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateMe")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(UpdateMeResponseObject); ok {
		return validResponse.VisitUpdateMeResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// HealthLive operation middleware
func (sh *strictHandler) HealthLive(ctx *echo.Context) error {
	var request HealthLiveRequestObject

	handler := func(ctx *echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.HealthLive(ctx.Request().Context(), request.(HealthLiveRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "HealthLive")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(HealthLiveResponseObject); ok {
		return validResponse.VisitHealthLiveResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// HealthReady operation middleware
func (sh *strictHandler) HealthReady(ctx *echo.Context) error {
	var request HealthReadyRequestObject

	handler := func(ctx *echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.HealthReady(ctx.Request().Context(), request.(HealthReadyRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "HealthReady")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(HealthReadyResponseObject); ok {
		return validResponse.VisitHealthReadyResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"1FlNc9s4D/4rHL7vUbGdj3a62lPabtt00mnGSXYPaaZhRNhmI5EqCTn1Zvzfd/ghWbIVK21td/dmiQIB",
	"PHgAgvADTVSWKwkSDY0fqAaTK2nAPRwXOAGJImEolHzDRArcvk+URJBof7I8T8N6/4tR0r4zyQQyZn/9",
	"X8OIxvR//YWSvl81/T+0VnoY1NH5fB5RDibRIreb0XhJOxk59T06j+grJUepSHB3tgzhawEGSRI0G3Iv",
	"cEKSQmuQSAwyBGfaG6VvBecgd2+bMEQqJDnoTCAGqE4kgpYsdbvszqZSLTGgp6AJWAFn0JAhnIpM4C6p",
	"dKEUyZicEe2xMj0a0QkwDtoRfQioZ3vHIwTtk+BrIbQ1EHUBUc2KTEiRFRmN9yOKsxxoTIVEGIO2aucR",
	"PQc9FQlcSjZlImW3KWzMy3fAUpysczMot0woFgY42P9kqeBO646ZULJzWhmwyOR5Ca0LQmVYrlUOGoUv",
	"QoniDsMAt0Et5Ni6lIExbNy2No9qIbzyOyy+v65Cp26/QIJ2r6YbKzZAaVonFCvKvWibzqV4rii1RaVw",
	"v0Bayl1RdUcjWotsbdtHXA97tKk/VWMhQ3QcBzgXNjwsPauZMWKpgWg5JKkAiZ/9lg9LAb80QG4kQzGF",
	"GzJSmhxLrpXghElOxMdz4qVdCpaO+c9pRO/htsWpiELGRGp1jZTOGNI4vIloxr6dghzjhMYHz45aRHNm",
	"zL3SvCFdvewCsFRTE6h7vwbYx8LKkgSM+Yzqzh8Sq75+y4UG81m4ZfjGstxWkRfPjwaDaOGCkPj8iK6W",
	"IWv/SIOZLFQsZyQWWgInSqYzFyEPfz0wK0a5vaqIl3F7CUyD7qZhw+fGZg1329A802okUvgxoqLI4G8l",
	"oQEkPTaC9d+zO6aRtfk6BW2EL4J1tA8PaLT+AGg6XSlf7Njm4NBHayOZ+OR86qSId+MxivxObrW6N6DL",
	"F6QwQJgk7xDzj1YmUepOQK8zv7qSaQhjYRD0j8GzxbJR22D/4IUjxuK5LYF+gIrdtajatQ27SwNt56nr",
	"WZNZnS8nr4ffWXZXPhVNpIpC8NbPzGtIAeun9q1SKTBpV7VKGzwurAcRZTxrVId2VL8rjzty1xlf+uqs",
	"iur5XGFYc2h9lttYPH4mcIadndalabHTCa7qs40VJIUWODu34l6Lr9b2WmWfbt3TmxKY939d0NCOuaC4",
	"1QVQE8Tct3dCjtRqxXh3cXFGjs9OXLH4oCSkakxY8wZnGwCWJKqQSHJf1m1XzsaQgURXKwS6tCg3OD47",
	"qeEa0/3eoDewcKocJMsFjelhb9A7dEmBE+dln+WiP93vW+X91J7FDm/li4dF3Vlzwmnsj2rqIQWDLxWf",
	"bawzbvRX82bgUBfgXtQu2weDwaZ1r7lbuwOZuPLv4hLqezgX/EJElK4KfbniC7txl4qjwf5jllSu9VuH",
	"CE74sFt4cZ22EgcH3RLLFx0n91u3XP1eWs8fGl9dR9QUWcb0jMb0lQaG7qzzTY1DrwTHgHFMtRss81AV",
	"uJaIdn07TFzqMJ7ExaPVFD/3zpERy0Rqr9JTdRemDLuK5Zq4DJ05BCcVifc8u725qyEJXz0ekwDbvygo",
	"OywQQ4UMgZeM/u+k+zqKOJ8I605XHbrOdeQIX2yLHc2290n02N+Y+ka30saOYB5w2/jrwI4nVNlqcvsT",
	"5fzZYNAt15x7ri8c3hfC7BhXcqa9Uw1WZGHQUbauTTL4DvADuDZEswzQzRWvlivoqzAuLpuf0NhErmkK",
	"lwJy84kefqI3th0SVsiPKWlEJbNW0JPR3geGyYQuE6I+p1y+SFw/pcAfh97MqBHueV/5JhJ/J7yY12N6",
	"vvDAnQjlnD50n1bLGFqy+i2gi+LW6m5XYpUMsQQsafKzIWgg8xawgUjQ4W+8llUrmFzmnAVyb6PSLc13",
	"dnwOdsXDO883Go9fkxLek7bYk+pi6yrexI2l+6kdIMUP7XniR9enfsa0teB0/+FxppXrwYUh1t6ePx6e",
	"0Gi0/E2z7owo9VglEoxpIKWB8VkHVEP3zS/F6jXkIDnIRIAhTANxdm8NskrdzCkSAbamRHMmcXVtzyn/",
	"j6E/Pgud0pj26fx6/s8A",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
