// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admin_access_events.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertAdminAccessEvent = `-- name: InsertAdminAccessEvent :one
INSERT INTO admin_access_events (
    id,
    actor_user_id,
    target_user_id,
    resource_type,
    resource_id,
    action,
    outcome,
    request_id,
    safe_metadata
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9
)
RETURNING id, actor_user_id, target_user_id, resource_type, resource_id, action, outcome, request_id, safe_metadata, created_at
`

type InsertAdminAccessEventParams struct {
	ID           pgtype.UUID `db:"id" json:"id"`
	ActorUserID  pgtype.UUID `db:"actor_user_id" json:"actor_user_id"`
	TargetUserID pgtype.UUID `db:"target_user_id" json:"target_user_id"`
	ResourceType string      `db:"resource_type" json:"resource_type"`
	ResourceID   pgtype.UUID `db:"resource_id" json:"resource_id"`
	Action       string      `db:"action" json:"action"`
	Outcome      string      `db:"outcome" json:"outcome"`
	RequestID    string      `db:"request_id" json:"request_id"`
	SafeMetadata []byte      `db:"safe_metadata" json:"safe_metadata"`
}

func (q *Queries) InsertAdminAccessEvent(ctx context.Context, arg InsertAdminAccessEventParams) (AdminAccessEvent, error) {
	row := q.db.QueryRow(ctx, insertAdminAccessEvent,
		arg.ID,
		arg.ActorUserID,
		arg.TargetUserID,
		arg.ResourceType,
		arg.ResourceID,
		arg.Action,
		arg.Outcome,
		arg.RequestID,
		arg.SafeMetadata,
	)
	var i AdminAccessEvent
	err := row.Scan(
		&i.ID,
		&i.ActorUserID,
		&i.TargetUserID,
		&i.ResourceType,
		&i.ResourceID,
		&i.Action,
		&i.Outcome,
		&i.RequestID,
		&i.SafeMetadata,
		&i.CreatedAt,
	)
	return i, err
}

const listAdminAccessEventsByActor = `-- name: ListAdminAccessEventsByActor :many
SELECT id, actor_user_id, target_user_id, resource_type, resource_id, action, outcome, request_id, safe_metadata, created_at
FROM admin_access_events
WHERE actor_user_id = $1
ORDER BY created_at DESC, id DESC
LIMIT $2
`

type ListAdminAccessEventsByActorParams struct {
	ActorUserID pgtype.UUID `db:"actor_user_id" json:"actor_user_id"`
	PageSize    int32       `db:"page_size" json:"page_size"`
}

func (q *Queries) ListAdminAccessEventsByActor(ctx context.Context, arg ListAdminAccessEventsByActorParams) ([]AdminAccessEvent, error) {
	rows, err := q.db.Query(ctx, listAdminAccessEventsByActor, arg.ActorUserID, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminAccessEvent{}
	for rows.Next() {
		var i AdminAccessEvent
		if err := rows.Scan(
			&i.ID,
			&i.ActorUserID,
			&i.TargetUserID,
			&i.ResourceType,
			&i.ResourceID,
			&i.Action,
			&i.Outcome,
			&i.RequestID,
			&i.SafeMetadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAdminAccessEventsByTarget = `-- name: ListAdminAccessEventsByTarget :many
SELECT id, actor_user_id, target_user_id, resource_type, resource_id, action, outcome, request_id, safe_metadata, created_at
FROM admin_access_events
WHERE target_user_id = $1
ORDER BY created_at DESC, id DESC
LIMIT $2
`

type ListAdminAccessEventsByTargetParams struct {
	TargetUserID pgtype.UUID `db:"target_user_id" json:"target_user_id"`
	PageSize     int32       `db:"page_size" json:"page_size"`
}

func (q *Queries) ListAdminAccessEventsByTarget(ctx context.Context, arg ListAdminAccessEventsByTargetParams) ([]AdminAccessEvent, error) {
	rows, err := q.db.Query(ctx, listAdminAccessEventsByTarget, arg.TargetUserID, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminAccessEvent{}
	for rows.Next() {
		var i AdminAccessEvent
		if err := rows.Scan(
			&i.ID,
			&i.ActorUserID,
			&i.TargetUserID,
			&i.ResourceType,
			&i.ResourceID,
			&i.Action,
			&i.Outcome,
			&i.RequestID,
			&i.SafeMetadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
