// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: categories.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCategory = `-- name: CreateCategory :one
INSERT INTO categories (id, user_id, type, name)
VALUES ($1, $2, $3, btrim($4))
RETURNING id, user_id, type, name, is_delete, version, created_at, updated_at
`

type CreateCategoryParams struct {
	ID     pgtype.UUID `db:"id" json:"id"`
	UserID pgtype.UUID `db:"user_id" json:"user_id"`
	Type   string      `db:"type" json:"type"`
	Name   string      `db:"name" json:"name"`
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, createCategory,
		arg.ID,
		arg.UserID,
		arg.Type,
		arg.Name,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Name,
		&i.IsDelete,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActiveCategory = `-- name: GetActiveCategory :one
SELECT id, user_id, type, name, is_delete, version, created_at, updated_at
FROM categories
WHERE id = $1
  AND user_id = $2
  AND is_delete = FALSE
`

type GetActiveCategoryParams struct {
	ID     pgtype.UUID `db:"id" json:"id"`
	UserID pgtype.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) GetActiveCategory(ctx context.Context, arg GetActiveCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, getActiveCategory, arg.ID, arg.UserID)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Name,
		&i.IsDelete,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDeletedCategory = `-- name: GetDeletedCategory :one
SELECT id, user_id, type, name, is_delete, version, created_at, updated_at
FROM categories
WHERE id = $1
  AND user_id = $2
  AND is_delete = TRUE
`

type GetDeletedCategoryParams struct {
	ID     pgtype.UUID `db:"id" json:"id"`
	UserID pgtype.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) GetDeletedCategory(ctx context.Context, arg GetDeletedCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, getDeletedCategory, arg.ID, arg.UserID)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Name,
		&i.IsDelete,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveCategories = `-- name: ListActiveCategories :many
SELECT id, user_id, type, name, is_delete, version, created_at, updated_at
FROM categories
WHERE user_id = $1
  AND is_delete = FALSE
ORDER BY type, lower(name), id
`

func (q *Queries) ListActiveCategories(ctx context.Context, userID pgtype.UUID) ([]Category, error) {
	rows, err := q.db.Query(ctx, listActiveCategories, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.Name,
			&i.IsDelete,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeletedCategories = `-- name: ListDeletedCategories :many
SELECT id, user_id, type, name, is_delete, version, created_at, updated_at
FROM categories
WHERE user_id = $1
  AND is_delete = TRUE
ORDER BY updated_at DESC, id DESC
`

func (q *Queries) ListDeletedCategories(ctx context.Context, userID pgtype.UUID) ([]Category, error) {
	rows, err := q.db.Query(ctx, listDeletedCategories, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.Name,
			&i.IsDelete,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restoreCategory = `-- name: RestoreCategory :one
UPDATE categories
SET is_delete = FALSE,
    version = version + 1,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
  AND user_id = $2
  AND version = $3
  AND is_delete = TRUE
RETURNING id, user_id, type, name, is_delete, version, created_at, updated_at
`

type RestoreCategoryParams struct {
	ID              pgtype.UUID `db:"id" json:"id"`
	UserID          pgtype.UUID `db:"user_id" json:"user_id"`
	ExpectedVersion int32       `db:"expected_version" json:"expected_version"`
}

func (q *Queries) RestoreCategory(ctx context.Context, arg RestoreCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, restoreCategory, arg.ID, arg.UserID, arg.ExpectedVersion)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Name,
		&i.IsDelete,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const softDeleteCategory = `-- name: SoftDeleteCategory :one
UPDATE categories
SET is_delete = TRUE,
    version = version + 1,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
  AND user_id = $2
  AND version = $3
  AND is_delete = FALSE
RETURNING id, user_id, type, name, is_delete, version, created_at, updated_at
`

type SoftDeleteCategoryParams struct {
	ID              pgtype.UUID `db:"id" json:"id"`
	UserID          pgtype.UUID `db:"user_id" json:"user_id"`
	ExpectedVersion int32       `db:"expected_version" json:"expected_version"`
}

func (q *Queries) SoftDeleteCategory(ctx context.Context, arg SoftDeleteCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, softDeleteCategory, arg.ID, arg.UserID, arg.ExpectedVersion)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Name,
		&i.IsDelete,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCategory = `-- name: UpdateCategory :one
UPDATE categories
SET name = btrim($1),
    version = version + 1,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $2
  AND user_id = $3
  AND version = $4
  AND is_delete = FALSE
RETURNING id, user_id, type, name, is_delete, version, created_at, updated_at
`

type UpdateCategoryParams struct {
	Name            string      `db:"name" json:"name"`
	ID              pgtype.UUID `db:"id" json:"id"`
	UserID          pgtype.UUID `db:"user_id" json:"user_id"`
	ExpectedVersion int32       `db:"expected_version" json:"expected_version"`
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, updateCategory,
		arg.Name,
		arg.ID,
		arg.UserID,
		arg.ExpectedVersion,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Name,
		&i.IsDelete,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
