// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AdminAccessEvent struct {
	ID           int64              `db:"id" json:"id"`
	ActorUserID  int64              `db:"actor_user_id" json:"actor_user_id"`
	TargetUserID *int64             `db:"target_user_id" json:"target_user_id"`
	ResourceType string             `db:"resource_type" json:"resource_type"`
	ResourceID   *int64             `db:"resource_id" json:"resource_id"`
	Action       string             `db:"action" json:"action"`
	Outcome      string             `db:"outcome" json:"outcome"`
	RequestID    string             `db:"request_id" json:"request_id"`
	SafeMetadata []byte             `db:"safe_metadata" json:"safe_metadata"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type Category struct {
	ID        int64              `db:"id" json:"id"`
	UserID    int64              `db:"user_id" json:"user_id"`
	Type      string             `db:"type" json:"type"`
	Name      string             `db:"name" json:"name"`
	IsDelete  bool               `db:"is_delete" json:"is_delete"`
	Version   int32              `db:"version" json:"version"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type RefreshSession struct {
	ID         int64              `db:"id" json:"id"`
	UserID     int64              `db:"user_id" json:"user_id"`
	FamilyID   int64              `db:"family_id" json:"family_id"`
	TokenHash  string             `db:"token_hash" json:"token_hash"`
	ExpiresAt  pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	RevokedAt  pgtype.Timestamptz `db:"revoked_at" json:"revoked_at"`
	ReplacedBy *int64             `db:"replaced_by" json:"replaced_by"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type Transaction struct {
	ID              int64              `db:"id" json:"id"`
	UserID          int64              `db:"user_id" json:"user_id"`
	CategoryID      int64              `db:"category_id" json:"category_id"`
	Type            string             `db:"type" json:"type"`
	Amount          pgtype.Numeric     `db:"amount" json:"amount"`
	TransactionDate pgtype.Date        `db:"transaction_date" json:"transaction_date"`
	Title           string             `db:"title" json:"title"`
	ClientRequestID int64              `db:"client_request_id" json:"client_request_id"`
	RequestHash     string             `db:"request_hash" json:"request_hash"`
	CreatedBy       int64              `db:"created_by" json:"created_by"`
	UpdatedBy       int64              `db:"updated_by" json:"updated_by"`
	IsDelete        bool               `db:"is_delete" json:"is_delete"`
	Version         int32              `db:"version" json:"version"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type User struct {
	ID           int64              `db:"id" json:"id"`
	Email        string             `db:"email" json:"email"`
	PasswordHash string             `db:"password_hash" json:"password_hash"`
	Role         string             `db:"role" json:"role"`
	Timezone     string             `db:"timezone" json:"timezone"`
	Currency     string             `db:"currency" json:"currency"`
	IsDelete     bool               `db:"is_delete" json:"is_delete"`
	Version      int32              `db:"version" json:"version"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}
