// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"
)

type Querier interface {
	CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error)
	CreateInitialAdmin(ctx context.Context, arg CreateInitialAdminParams) (User, error)
	// Create a refresh session after successful login or refresh rotation.
	CreateRefreshSession(ctx context.Context, arg CreateRefreshSessionParams) (RefreshSession, error)
	CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error)
	CreateTransactionTemplate(ctx context.Context, arg CreateTransactionTemplateParams) (TransactionTemplate, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetActiveCategory(ctx context.Context, arg GetActiveCategoryParams) (Category, error)
	GetActiveTransaction(ctx context.Context, arg GetActiveTransactionParams) (GetActiveTransactionRow, error)
	GetActiveTransactionTemplate(ctx context.Context, arg GetActiveTransactionTemplateParams) (TransactionTemplate, error)
	GetActiveUserByEmail(ctx context.Context, email string) (User, error)
	GetActiveUserByID(ctx context.Context, id int64) (User, error)
	GetCategoryByID(ctx context.Context, arg GetCategoryByIDParams) (Category, error)
	GetDeletedCategory(ctx context.Context, arg GetDeletedCategoryParams) (Category, error)
	GetDeletedTransaction(ctx context.Context, arg GetDeletedTransactionParams) (GetDeletedTransactionRow, error)
	GetDeletedTransactionTemplate(ctx context.Context, arg GetDeletedTransactionTemplateParams) (TransactionTemplate, error)
	// Find a refresh session for validation without taking a write lock.
	GetRefreshSessionByTokenHash(ctx context.Context, tokenHash string) (RefreshSession, error)
	// Find and lock a refresh session before rotating or revoking it.
	GetRefreshSessionByTokenHashForUpdate(ctx context.Context, tokenHash string) (RefreshSession, error)
	GetReportSummary(ctx context.Context, arg GetReportSummaryParams) (GetReportSummaryRow, error)
	GetTransactionByRequestIDForUpdate(ctx context.Context, arg GetTransactionByRequestIDForUpdateParams) (Transaction, error)
	GetTransactionStateForUpdate(ctx context.Context, arg GetTransactionStateForUpdateParams) (Transaction, error)
	GetTransactionTemplateStateForUpdate(ctx context.Context, arg GetTransactionTemplateStateForUpdateParams) (TransactionTemplate, error)
	GetUserByID(ctx context.Context, id int64) (User, error)
	InsertAdminAccessEvent(ctx context.Context, arg InsertAdminAccessEventParams) (AdminAccessEvent, error)
	ListActiveCategories(ctx context.Context, userID int64) ([]Category, error)
	ListActiveTransactionTemplates(ctx context.Context, userID int64) ([]TransactionTemplate, error)
	ListActiveTransactions(ctx context.Context, arg ListActiveTransactionsParams) ([]ListActiveTransactionsRow, error)
	ListAdminAccessEventsByActor(ctx context.Context, arg ListAdminAccessEventsByActorParams) ([]AdminAccessEvent, error)
	ListAdminAccessEventsByTarget(ctx context.Context, arg ListAdminAccessEventsByTargetParams) ([]AdminAccessEvent, error)
	ListDailySummaries(ctx context.Context, arg ListDailySummariesParams) ([]ListDailySummariesRow, error)
	ListDeletedCategories(ctx context.Context, userID int64) ([]Category, error)
	ListDeletedTransactionTemplates(ctx context.Context, userID int64) ([]TransactionTemplate, error)
	ListDeletedTransactions(ctx context.Context, arg ListDeletedTransactionsParams) ([]ListDeletedTransactionsRow, error)
	ListReportCategoryBreakdown(ctx context.Context, arg ListReportCategoryBreakdownParams) ([]ListReportCategoryBreakdownRow, error)
	ListReportPeriodBreakdown(ctx context.Context, arg ListReportPeriodBreakdownParams) ([]ListReportPeriodBreakdownRow, error)
	ListTopReportCategories(ctx context.Context, arg ListTopReportCategoriesParams) ([]ListTopReportCategoriesRow, error)
	LockInitialAdminBootstrap(ctx context.Context) error
	LockScopedCategoryForTemplate(ctx context.Context, arg LockScopedCategoryForTemplateParams) (Category, error)
	LockScopedCategoryForTransaction(ctx context.Context, arg LockScopedCategoryForTransactionParams) (Category, error)
	LockUsersForUpdate(ctx context.Context, ids []int64) ([]User, error)
	RestoreCategory(ctx context.Context, arg RestoreCategoryParams) (Category, error)
	RestoreTransaction(ctx context.Context, arg RestoreTransactionParams) (Transaction, error)
	RestoreTransactionTemplate(ctx context.Context, arg RestoreTransactionTemplateParams) (TransactionTemplate, error)
	RestoreUser(ctx context.Context, arg RestoreUserParams) (User, error)
	// Revoke all active refresh sessions for a user during account deletion or security action.
	RevokeAllUserRefreshSessions(ctx context.Context, userID int64) (int64, error)
	// Revoke one active refresh session and optionally link its replacement.
	RevokeRefreshSession(ctx context.Context, arg RevokeRefreshSessionParams) (RefreshSession, error)
	// Revoke every active session in one refresh-token family during logout or reuse detection.
	RevokeRefreshSessionFamily(ctx context.Context, arg RevokeRefreshSessionFamilyParams) (int64, error)
	SoftDeleteCategory(ctx context.Context, arg SoftDeleteCategoryParams) (Category, error)
	SoftDeleteTransaction(ctx context.Context, arg SoftDeleteTransactionParams) (Transaction, error)
	SoftDeleteTransactionTemplate(ctx context.Context, arg SoftDeleteTransactionTemplateParams) (TransactionTemplate, error)
	SoftDeleteUser(ctx context.Context, arg SoftDeleteUserParams) (User, error)
	UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error)
	UpdateTransaction(ctx context.Context, arg UpdateTransactionParams) (Transaction, error)
	UpdateTransactionTemplate(ctx context.Context, arg UpdateTransactionTemplateParams) (TransactionTemplate, error)
	UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error)
}

var _ Querier = (*Queries)(nil)
