// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error)
	CreateInitialAdmin(ctx context.Context, arg CreateInitialAdminParams) (User, error)
	CreateRefreshSession(ctx context.Context, arg CreateRefreshSessionParams) (RefreshSession, error)
	CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetActiveCategory(ctx context.Context, arg GetActiveCategoryParams) (Category, error)
	GetActiveTransaction(ctx context.Context, arg GetActiveTransactionParams) (Transaction, error)
	GetActiveUserByEmail(ctx context.Context, email string) (User, error)
	GetActiveUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	GetDeletedCategory(ctx context.Context, arg GetDeletedCategoryParams) (Category, error)
	GetRefreshSessionByTokenHash(ctx context.Context, tokenHash string) (RefreshSession, error)
	GetRefreshSessionByTokenHashForUpdate(ctx context.Context, tokenHash string) (RefreshSession, error)
	GetTransactionByRequestID(ctx context.Context, arg GetTransactionByRequestIDParams) (Transaction, error)
	InsertAdminAccessEvent(ctx context.Context, arg InsertAdminAccessEventParams) (AdminAccessEvent, error)
	ListActiveCategories(ctx context.Context, userID pgtype.UUID) ([]Category, error)
	ListActiveTransactions(ctx context.Context, arg ListActiveTransactionsParams) ([]Transaction, error)
	ListAdminAccessEventsByActor(ctx context.Context, arg ListAdminAccessEventsByActorParams) ([]AdminAccessEvent, error)
	ListAdminAccessEventsByTarget(ctx context.Context, arg ListAdminAccessEventsByTargetParams) ([]AdminAccessEvent, error)
	ListDeletedCategories(ctx context.Context, userID pgtype.UUID) ([]Category, error)
	ListDeletedTransactions(ctx context.Context, arg ListDeletedTransactionsParams) ([]Transaction, error)
	LockInitialAdminBootstrap(ctx context.Context) error
	LockUsersForUpdate(ctx context.Context, ids []pgtype.UUID) ([]User, error)
	RestoreCategory(ctx context.Context, arg RestoreCategoryParams) (Category, error)
	RestoreTransaction(ctx context.Context, arg RestoreTransactionParams) (Transaction, error)
	RestoreUser(ctx context.Context, arg RestoreUserParams) (User, error)
	RevokeAllUserRefreshSessions(ctx context.Context, userID pgtype.UUID) (int64, error)
	RevokeRefreshSession(ctx context.Context, arg RevokeRefreshSessionParams) (RefreshSession, error)
	RevokeRefreshSessionFamily(ctx context.Context, arg RevokeRefreshSessionFamilyParams) (int64, error)
	SoftDeleteCategory(ctx context.Context, arg SoftDeleteCategoryParams) (Category, error)
	SoftDeleteTransaction(ctx context.Context, arg SoftDeleteTransactionParams) (Transaction, error)
	SoftDeleteUser(ctx context.Context, arg SoftDeleteUserParams) (User, error)
	UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error)
	UpdateTransaction(ctx context.Context, arg UpdateTransactionParams) (Transaction, error)
	UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error)
}

var _ Querier = (*Queries)(nil)
