// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: refresh_sessions.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRefreshSession = `-- name: CreateRefreshSession :one
INSERT INTO refresh_sessions (
    id,
    user_id,
    family_id,
    token_hash,
    expires_at
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
RETURNING id, user_id, family_id, token_hash, expires_at, revoked_at, replaced_by, created_at
`

type CreateRefreshSessionParams struct {
	ID        pgtype.UUID        `db:"id" json:"id"`
	UserID    pgtype.UUID        `db:"user_id" json:"user_id"`
	FamilyID  pgtype.UUID        `db:"family_id" json:"family_id"`
	TokenHash string             `db:"token_hash" json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
}

// Create a refresh session after successful login or refresh rotation.
func (q *Queries) CreateRefreshSession(ctx context.Context, arg CreateRefreshSessionParams) (RefreshSession, error) {
	row := q.db.QueryRow(ctx, createRefreshSession,
		arg.ID,
		arg.UserID,
		arg.FamilyID,
		arg.TokenHash,
		arg.ExpiresAt,
	)
	var i RefreshSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FamilyID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.ReplacedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getRefreshSessionByTokenHash = `-- name: GetRefreshSessionByTokenHash :one
SELECT id, user_id, family_id, token_hash, expires_at, revoked_at, replaced_by, created_at
FROM refresh_sessions
WHERE token_hash = $1
`

// Find a refresh session for validation without taking a write lock.
func (q *Queries) GetRefreshSessionByTokenHash(ctx context.Context, tokenHash string) (RefreshSession, error) {
	row := q.db.QueryRow(ctx, getRefreshSessionByTokenHash, tokenHash)
	var i RefreshSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FamilyID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.ReplacedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getRefreshSessionByTokenHashForUpdate = `-- name: GetRefreshSessionByTokenHashForUpdate :one
SELECT id, user_id, family_id, token_hash, expires_at, revoked_at, replaced_by, created_at
FROM refresh_sessions
WHERE token_hash = $1
FOR UPDATE
`

// Find and lock a refresh session before rotating or revoking it.
func (q *Queries) GetRefreshSessionByTokenHashForUpdate(ctx context.Context, tokenHash string) (RefreshSession, error) {
	row := q.db.QueryRow(ctx, getRefreshSessionByTokenHashForUpdate, tokenHash)
	var i RefreshSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FamilyID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.ReplacedBy,
		&i.CreatedAt,
	)
	return i, err
}

const revokeAllUserRefreshSessions = `-- name: RevokeAllUserRefreshSessions :execrows
UPDATE refresh_sessions
SET revoked_at = CURRENT_TIMESTAMP
WHERE user_id = $1
  AND revoked_at IS NULL
`

// Revoke all active refresh sessions for a user during account deletion or security action.
func (q *Queries) RevokeAllUserRefreshSessions(ctx context.Context, userID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, revokeAllUserRefreshSessions, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeRefreshSession = `-- name: RevokeRefreshSession :one
UPDATE refresh_sessions
SET revoked_at = COALESCE(revoked_at, CURRENT_TIMESTAMP),
    replaced_by = $1
WHERE id = $2
  AND revoked_at IS NULL
RETURNING id, user_id, family_id, token_hash, expires_at, revoked_at, replaced_by, created_at
`

type RevokeRefreshSessionParams struct {
	ReplacedBy pgtype.UUID `db:"replaced_by" json:"replaced_by"`
	ID         pgtype.UUID `db:"id" json:"id"`
}

// Revoke one active refresh session and optionally link its replacement.
func (q *Queries) RevokeRefreshSession(ctx context.Context, arg RevokeRefreshSessionParams) (RefreshSession, error) {
	row := q.db.QueryRow(ctx, revokeRefreshSession, arg.ReplacedBy, arg.ID)
	var i RefreshSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FamilyID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.ReplacedBy,
		&i.CreatedAt,
	)
	return i, err
}

const revokeRefreshSessionFamily = `-- name: RevokeRefreshSessionFamily :execrows
UPDATE refresh_sessions
SET revoked_at = CURRENT_TIMESTAMP
WHERE user_id = $1
  AND family_id = $2
  AND revoked_at IS NULL
`

type RevokeRefreshSessionFamilyParams struct {
	UserID   pgtype.UUID `db:"user_id" json:"user_id"`
	FamilyID pgtype.UUID `db:"family_id" json:"family_id"`
}

// Revoke every active session in one refresh-token family during logout or reuse detection.
func (q *Queries) RevokeRefreshSessionFamily(ctx context.Context, arg RevokeRefreshSessionFamilyParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeRefreshSessionFamily, arg.UserID, arg.FamilyID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
