// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: templates.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTransactionTemplate = `-- name: CreateTransactionTemplate :one
INSERT INTO transaction_templates (user_id, category_id, type, name, amount, title)
SELECT $1, $2, $3,
       btrim($4), $5, btrim($6)
FROM categories
WHERE id = $2
  AND user_id = $1
  AND type = $3
  AND is_delete = FALSE
RETURNING transaction_templates.id, transaction_templates.user_id, transaction_templates.category_id, transaction_templates.type, transaction_templates.name, transaction_templates.amount, transaction_templates.title, transaction_templates.is_delete, transaction_templates.version, transaction_templates.created_at, transaction_templates.updated_at
`

type CreateTransactionTemplateParams struct {
	UserID     int64          `db:"user_id" json:"user_id"`
	CategoryID int64          `db:"category_id" json:"category_id"`
	Type       string         `db:"type" json:"type"`
	Name       string         `db:"name" json:"name"`
	Amount     pgtype.Numeric `db:"amount" json:"amount"`
	Title      string         `db:"title" json:"title"`
}

func (q *Queries) CreateTransactionTemplate(ctx context.Context, arg CreateTransactionTemplateParams) (TransactionTemplate, error) {
	row := q.db.QueryRow(ctx, createTransactionTemplate,
		arg.UserID,
		arg.CategoryID,
		arg.Type,
		arg.Name,
		arg.Amount,
		arg.Title,
	)
	var i TransactionTemplate
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CategoryID,
		&i.Type,
		&i.Name,
		&i.Amount,
		&i.Title,
		&i.IsDelete,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActiveTransactionTemplate = `-- name: GetActiveTransactionTemplate :one
SELECT id, user_id, category_id, type, name, amount, title, is_delete, version, created_at, updated_at FROM transaction_templates
WHERE id = $1
  AND user_id = $2
  AND is_delete = FALSE
`

type GetActiveTransactionTemplateParams struct {
	ID     int64 `db:"id" json:"id"`
	UserID int64 `db:"user_id" json:"user_id"`
}

func (q *Queries) GetActiveTransactionTemplate(ctx context.Context, arg GetActiveTransactionTemplateParams) (TransactionTemplate, error) {
	row := q.db.QueryRow(ctx, getActiveTransactionTemplate, arg.ID, arg.UserID)
	var i TransactionTemplate
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CategoryID,
		&i.Type,
		&i.Name,
		&i.Amount,
		&i.Title,
		&i.IsDelete,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDeletedTransactionTemplate = `-- name: GetDeletedTransactionTemplate :one
SELECT id, user_id, category_id, type, name, amount, title, is_delete, version, created_at, updated_at FROM transaction_templates
WHERE id = $1
  AND user_id = $2
  AND is_delete = TRUE
`

type GetDeletedTransactionTemplateParams struct {
	ID     int64 `db:"id" json:"id"`
	UserID int64 `db:"user_id" json:"user_id"`
}

func (q *Queries) GetDeletedTransactionTemplate(ctx context.Context, arg GetDeletedTransactionTemplateParams) (TransactionTemplate, error) {
	row := q.db.QueryRow(ctx, getDeletedTransactionTemplate, arg.ID, arg.UserID)
	var i TransactionTemplate
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CategoryID,
		&i.Type,
		&i.Name,
		&i.Amount,
		&i.Title,
		&i.IsDelete,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTransactionTemplateStateForUpdate = `-- name: GetTransactionTemplateStateForUpdate :one
SELECT id, user_id, category_id, type, name, amount, title, is_delete, version, created_at, updated_at FROM transaction_templates
WHERE id = $1
  AND user_id = $2
FOR UPDATE
`

type GetTransactionTemplateStateForUpdateParams struct {
	ID     int64 `db:"id" json:"id"`
	UserID int64 `db:"user_id" json:"user_id"`
}

func (q *Queries) GetTransactionTemplateStateForUpdate(ctx context.Context, arg GetTransactionTemplateStateForUpdateParams) (TransactionTemplate, error) {
	row := q.db.QueryRow(ctx, getTransactionTemplateStateForUpdate, arg.ID, arg.UserID)
	var i TransactionTemplate
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CategoryID,
		&i.Type,
		&i.Name,
		&i.Amount,
		&i.Title,
		&i.IsDelete,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveTransactionTemplates = `-- name: ListActiveTransactionTemplates :many
SELECT id, user_id, category_id, type, name, amount, title, is_delete, version, created_at, updated_at FROM transaction_templates
WHERE user_id = $1
  AND is_delete = FALSE
ORDER BY lower(name), id
`

func (q *Queries) ListActiveTransactionTemplates(ctx context.Context, userID int64) ([]TransactionTemplate, error) {
	rows, err := q.db.Query(ctx, listActiveTransactionTemplates, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TransactionTemplate{}
	for rows.Next() {
		var i TransactionTemplate
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CategoryID,
			&i.Type,
			&i.Name,
			&i.Amount,
			&i.Title,
			&i.IsDelete,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeletedTransactionTemplates = `-- name: ListDeletedTransactionTemplates :many
SELECT id, user_id, category_id, type, name, amount, title, is_delete, version, created_at, updated_at FROM transaction_templates
WHERE user_id = $1
  AND is_delete = TRUE
ORDER BY updated_at DESC, id DESC
`

func (q *Queries) ListDeletedTransactionTemplates(ctx context.Context, userID int64) ([]TransactionTemplate, error) {
	rows, err := q.db.Query(ctx, listDeletedTransactionTemplates, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TransactionTemplate{}
	for rows.Next() {
		var i TransactionTemplate
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CategoryID,
			&i.Type,
			&i.Name,
			&i.Amount,
			&i.Title,
			&i.IsDelete,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockScopedCategoryForTemplate = `-- name: LockScopedCategoryForTemplate :one
SELECT id, user_id, type, name, is_delete, version, created_at, updated_at FROM categories
WHERE id = $1 AND user_id = $2
FOR UPDATE
`

type LockScopedCategoryForTemplateParams struct {
	CategoryID int64 `db:"category_id" json:"category_id"`
	UserID     int64 `db:"user_id" json:"user_id"`
}

func (q *Queries) LockScopedCategoryForTemplate(ctx context.Context, arg LockScopedCategoryForTemplateParams) (Category, error) {
	row := q.db.QueryRow(ctx, lockScopedCategoryForTemplate, arg.CategoryID, arg.UserID)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Name,
		&i.IsDelete,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const restoreTransactionTemplate = `-- name: RestoreTransactionTemplate :one
UPDATE transaction_templates
SET is_delete = FALSE,
    version = version + 1,
    updated_at = CURRENT_TIMESTAMP
WHERE transaction_templates.id = $1
  AND transaction_templates.user_id = $2
  AND transaction_templates.version = $3
  AND transaction_templates.is_delete = TRUE
  AND EXISTS (
      SELECT 1 FROM categories
      WHERE categories.id = transaction_templates.category_id
        AND categories.user_id = transaction_templates.user_id
        AND categories.type = transaction_templates.type
        AND categories.is_delete = FALSE
  )
RETURNING id, user_id, category_id, type, name, amount, title, is_delete, version, created_at, updated_at
`

type RestoreTransactionTemplateParams struct {
	ID              int64 `db:"id" json:"id"`
	UserID          int64 `db:"user_id" json:"user_id"`
	ExpectedVersion int32 `db:"expected_version" json:"expected_version"`
}

func (q *Queries) RestoreTransactionTemplate(ctx context.Context, arg RestoreTransactionTemplateParams) (TransactionTemplate, error) {
	row := q.db.QueryRow(ctx, restoreTransactionTemplate, arg.ID, arg.UserID, arg.ExpectedVersion)
	var i TransactionTemplate
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CategoryID,
		&i.Type,
		&i.Name,
		&i.Amount,
		&i.Title,
		&i.IsDelete,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const softDeleteTransactionTemplate = `-- name: SoftDeleteTransactionTemplate :one
UPDATE transaction_templates
SET is_delete = TRUE,
    version = version + 1,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
  AND user_id = $2
  AND version = $3
  AND is_delete = FALSE
RETURNING id, user_id, category_id, type, name, amount, title, is_delete, version, created_at, updated_at
`

type SoftDeleteTransactionTemplateParams struct {
	ID              int64 `db:"id" json:"id"`
	UserID          int64 `db:"user_id" json:"user_id"`
	ExpectedVersion int32 `db:"expected_version" json:"expected_version"`
}

func (q *Queries) SoftDeleteTransactionTemplate(ctx context.Context, arg SoftDeleteTransactionTemplateParams) (TransactionTemplate, error) {
	row := q.db.QueryRow(ctx, softDeleteTransactionTemplate, arg.ID, arg.UserID, arg.ExpectedVersion)
	var i TransactionTemplate
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CategoryID,
		&i.Type,
		&i.Name,
		&i.Amount,
		&i.Title,
		&i.IsDelete,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTransactionTemplate = `-- name: UpdateTransactionTemplate :one
UPDATE transaction_templates
SET category_id = $1,
    type = $2,
    name = btrim($3),
    amount = $4,
    title = btrim($5),
    version = version + 1,
    updated_at = CURRENT_TIMESTAMP
WHERE transaction_templates.id = $6
  AND transaction_templates.user_id = $7
  AND transaction_templates.version = $8
  AND transaction_templates.is_delete = FALSE
  AND EXISTS (
      SELECT 1 FROM categories
      WHERE categories.id = $1
        AND categories.user_id = $7
        AND categories.type = $2
        AND categories.is_delete = FALSE
  )
RETURNING id, user_id, category_id, type, name, amount, title, is_delete, version, created_at, updated_at
`

type UpdateTransactionTemplateParams struct {
	CategoryID      int64          `db:"category_id" json:"category_id"`
	Type            string         `db:"type" json:"type"`
	Name            string         `db:"name" json:"name"`
	Amount          pgtype.Numeric `db:"amount" json:"amount"`
	Title           string         `db:"title" json:"title"`
	ID              int64          `db:"id" json:"id"`
	UserID          int64          `db:"user_id" json:"user_id"`
	ExpectedVersion int32          `db:"expected_version" json:"expected_version"`
}

func (q *Queries) UpdateTransactionTemplate(ctx context.Context, arg UpdateTransactionTemplateParams) (TransactionTemplate, error) {
	row := q.db.QueryRow(ctx, updateTransactionTemplate,
		arg.CategoryID,
		arg.Type,
		arg.Name,
		arg.Amount,
		arg.Title,
		arg.ID,
		arg.UserID,
		arg.ExpectedVersion,
	)
	var i TransactionTemplate
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CategoryID,
		&i.Type,
		&i.Name,
		&i.Amount,
		&i.Title,
		&i.IsDelete,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
