// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: transactions.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions (
    id,
    user_id,
    category_id,
    type,
    amount,
    transaction_date,
    title,
    client_request_id,
    request_hash,
    created_by,
    updated_by
)
SELECT
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    btrim($7),
    $8,
    $9,
    $10,
    $10
FROM categories
WHERE categories.id = $3
  AND categories.user_id = $2
  AND categories.type = $4
  AND categories.is_delete = FALSE
RETURNING transactions.id, transactions.user_id, transactions.category_id, transactions.type, transactions.amount, transactions.transaction_date, transactions.title, transactions.client_request_id, transactions.request_hash, transactions.created_by, transactions.updated_by, transactions.is_delete, transactions.version, transactions.created_at, transactions.updated_at
`

type CreateTransactionParams struct {
	ID              pgtype.UUID    `db:"id" json:"id"`
	UserID          pgtype.UUID    `db:"user_id" json:"user_id"`
	CategoryID      pgtype.UUID    `db:"category_id" json:"category_id"`
	Type            string         `db:"type" json:"type"`
	Amount          pgtype.Numeric `db:"amount" json:"amount"`
	TransactionDate pgtype.Date    `db:"transaction_date" json:"transaction_date"`
	Title           string         `db:"title" json:"title"`
	ClientRequestID pgtype.UUID    `db:"client_request_id" json:"client_request_id"`
	RequestHash     string         `db:"request_hash" json:"request_hash"`
	ActorUserID     pgtype.UUID    `db:"actor_user_id" json:"actor_user_id"`
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, createTransaction,
		arg.ID,
		arg.UserID,
		arg.CategoryID,
		arg.Type,
		arg.Amount,
		arg.TransactionDate,
		arg.Title,
		arg.ClientRequestID,
		arg.RequestHash,
		arg.ActorUserID,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CategoryID,
		&i.Type,
		&i.Amount,
		&i.TransactionDate,
		&i.Title,
		&i.ClientRequestID,
		&i.RequestHash,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.IsDelete,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActiveTransaction = `-- name: GetActiveTransaction :one
SELECT id, user_id, category_id, type, amount, transaction_date, title, client_request_id, request_hash, created_by, updated_by, is_delete, version, created_at, updated_at
FROM transactions
WHERE id = $1
  AND user_id = $2
  AND is_delete = FALSE
`

type GetActiveTransactionParams struct {
	ID     pgtype.UUID `db:"id" json:"id"`
	UserID pgtype.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) GetActiveTransaction(ctx context.Context, arg GetActiveTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, getActiveTransaction, arg.ID, arg.UserID)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CategoryID,
		&i.Type,
		&i.Amount,
		&i.TransactionDate,
		&i.Title,
		&i.ClientRequestID,
		&i.RequestHash,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.IsDelete,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTransactionByRequestID = `-- name: GetTransactionByRequestID :one
SELECT id, user_id, category_id, type, amount, transaction_date, title, client_request_id, request_hash, created_by, updated_by, is_delete, version, created_at, updated_at
FROM transactions
WHERE user_id = $1
  AND client_request_id = $2
`

type GetTransactionByRequestIDParams struct {
	UserID          pgtype.UUID `db:"user_id" json:"user_id"`
	ClientRequestID pgtype.UUID `db:"client_request_id" json:"client_request_id"`
}

func (q *Queries) GetTransactionByRequestID(ctx context.Context, arg GetTransactionByRequestIDParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, getTransactionByRequestID, arg.UserID, arg.ClientRequestID)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CategoryID,
		&i.Type,
		&i.Amount,
		&i.TransactionDate,
		&i.Title,
		&i.ClientRequestID,
		&i.RequestHash,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.IsDelete,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveTransactions = `-- name: ListActiveTransactions :many
SELECT id, user_id, category_id, type, amount, transaction_date, title, client_request_id, request_hash, created_by, updated_by, is_delete, version, created_at, updated_at
FROM transactions
WHERE user_id = $1
  AND is_delete = FALSE
ORDER BY transaction_date DESC, id DESC
LIMIT $2
`

type ListActiveTransactionsParams struct {
	UserID   pgtype.UUID `db:"user_id" json:"user_id"`
	PageSize int32       `db:"page_size" json:"page_size"`
}

func (q *Queries) ListActiveTransactions(ctx context.Context, arg ListActiveTransactionsParams) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, listActiveTransactions, arg.UserID, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transaction{}
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CategoryID,
			&i.Type,
			&i.Amount,
			&i.TransactionDate,
			&i.Title,
			&i.ClientRequestID,
			&i.RequestHash,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.IsDelete,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeletedTransactions = `-- name: ListDeletedTransactions :many
SELECT id, user_id, category_id, type, amount, transaction_date, title, client_request_id, request_hash, created_by, updated_by, is_delete, version, created_at, updated_at
FROM transactions
WHERE user_id = $1
  AND is_delete = TRUE
ORDER BY updated_at DESC, id DESC
LIMIT $2
`

type ListDeletedTransactionsParams struct {
	UserID   pgtype.UUID `db:"user_id" json:"user_id"`
	PageSize int32       `db:"page_size" json:"page_size"`
}

func (q *Queries) ListDeletedTransactions(ctx context.Context, arg ListDeletedTransactionsParams) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, listDeletedTransactions, arg.UserID, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transaction{}
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CategoryID,
			&i.Type,
			&i.Amount,
			&i.TransactionDate,
			&i.Title,
			&i.ClientRequestID,
			&i.RequestHash,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.IsDelete,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restoreTransaction = `-- name: RestoreTransaction :one
UPDATE transactions
SET is_delete = FALSE,
    updated_by = $1,
    version = version + 1,
    updated_at = CURRENT_TIMESTAMP
WHERE transactions.id = $2
  AND transactions.user_id = $3
  AND transactions.version = $4
  AND transactions.is_delete = TRUE
  AND EXISTS (
      SELECT 1
      FROM categories
      WHERE categories.id = transactions.category_id
        AND categories.user_id = transactions.user_id
        AND categories.type = transactions.type
        AND categories.is_delete = FALSE
  )
RETURNING id, user_id, category_id, type, amount, transaction_date, title, client_request_id, request_hash, created_by, updated_by, is_delete, version, created_at, updated_at
`

type RestoreTransactionParams struct {
	ActorUserID     pgtype.UUID `db:"actor_user_id" json:"actor_user_id"`
	ID              pgtype.UUID `db:"id" json:"id"`
	UserID          pgtype.UUID `db:"user_id" json:"user_id"`
	ExpectedVersion int32       `db:"expected_version" json:"expected_version"`
}

func (q *Queries) RestoreTransaction(ctx context.Context, arg RestoreTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, restoreTransaction,
		arg.ActorUserID,
		arg.ID,
		arg.UserID,
		arg.ExpectedVersion,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CategoryID,
		&i.Type,
		&i.Amount,
		&i.TransactionDate,
		&i.Title,
		&i.ClientRequestID,
		&i.RequestHash,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.IsDelete,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const softDeleteTransaction = `-- name: SoftDeleteTransaction :one
UPDATE transactions
SET is_delete = TRUE,
    updated_by = $1,
    version = version + 1,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $2
  AND user_id = $3
  AND version = $4
  AND is_delete = FALSE
RETURNING id, user_id, category_id, type, amount, transaction_date, title, client_request_id, request_hash, created_by, updated_by, is_delete, version, created_at, updated_at
`

type SoftDeleteTransactionParams struct {
	ActorUserID     pgtype.UUID `db:"actor_user_id" json:"actor_user_id"`
	ID              pgtype.UUID `db:"id" json:"id"`
	UserID          pgtype.UUID `db:"user_id" json:"user_id"`
	ExpectedVersion int32       `db:"expected_version" json:"expected_version"`
}

func (q *Queries) SoftDeleteTransaction(ctx context.Context, arg SoftDeleteTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, softDeleteTransaction,
		arg.ActorUserID,
		arg.ID,
		arg.UserID,
		arg.ExpectedVersion,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CategoryID,
		&i.Type,
		&i.Amount,
		&i.TransactionDate,
		&i.Title,
		&i.ClientRequestID,
		&i.RequestHash,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.IsDelete,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTransaction = `-- name: UpdateTransaction :one
UPDATE transactions
SET category_id = $1,
    type = $2,
    amount = $3,
    transaction_date = $4,
    title = btrim($5),
    updated_by = $6,
    version = version + 1,
    updated_at = CURRENT_TIMESTAMP
WHERE transactions.id = $7
  AND transactions.user_id = $8
  AND transactions.version = $9
  AND transactions.is_delete = FALSE
  AND EXISTS (
      SELECT 1
      FROM categories
      WHERE categories.id = $1
        AND categories.user_id = $8
        AND categories.type = $2
        AND categories.is_delete = FALSE
  )
RETURNING id, user_id, category_id, type, amount, transaction_date, title, client_request_id, request_hash, created_by, updated_by, is_delete, version, created_at, updated_at
`

type UpdateTransactionParams struct {
	CategoryID      pgtype.UUID    `db:"category_id" json:"category_id"`
	Type            string         `db:"type" json:"type"`
	Amount          pgtype.Numeric `db:"amount" json:"amount"`
	TransactionDate pgtype.Date    `db:"transaction_date" json:"transaction_date"`
	Title           string         `db:"title" json:"title"`
	ActorUserID     pgtype.UUID    `db:"actor_user_id" json:"actor_user_id"`
	ID              pgtype.UUID    `db:"id" json:"id"`
	UserID          pgtype.UUID    `db:"user_id" json:"user_id"`
	ExpectedVersion int32          `db:"expected_version" json:"expected_version"`
}

func (q *Queries) UpdateTransaction(ctx context.Context, arg UpdateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, updateTransaction,
		arg.CategoryID,
		arg.Type,
		arg.Amount,
		arg.TransactionDate,
		arg.Title,
		arg.ActorUserID,
		arg.ID,
		arg.UserID,
		arg.ExpectedVersion,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CategoryID,
		&i.Type,
		&i.Amount,
		&i.TransactionDate,
		&i.Title,
		&i.ClientRequestID,
		&i.RequestHash,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.IsDelete,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
