// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: transactions.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions (
    user_id, category_id, type, amount, transaction_date, title,
    client_request_id, request_hash, created_by, updated_by
)
SELECT $1, $2, $3,
       $4, $5, btrim($6),
       $7, $8,
       $9, $9
FROM categories
WHERE categories.id = $2
  AND categories.user_id = $1
  AND categories.type = $3
  AND categories.is_delete = FALSE
ON CONFLICT (user_id, client_request_id) DO NOTHING
RETURNING transactions.id, transactions.user_id, transactions.category_id, transactions.type, transactions.amount, transactions.transaction_date, transactions.title, transactions.client_request_id, transactions.request_hash, transactions.created_by, transactions.updated_by, transactions.is_delete, transactions.version, transactions.created_at, transactions.updated_at
`

type CreateTransactionParams struct {
	UserID          int64          `db:"user_id" json:"user_id"`
	CategoryID      int64          `db:"category_id" json:"category_id"`
	Type            string         `db:"type" json:"type"`
	Amount          pgtype.Numeric `db:"amount" json:"amount"`
	TransactionDate pgtype.Date    `db:"transaction_date" json:"transaction_date"`
	Title           string         `db:"title" json:"title"`
	ClientRequestID int64          `db:"client_request_id" json:"client_request_id"`
	RequestHash     string         `db:"request_hash" json:"request_hash"`
	ActorUserID     int64          `db:"actor_user_id" json:"actor_user_id"`
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, createTransaction,
		arg.UserID,
		arg.CategoryID,
		arg.Type,
		arg.Amount,
		arg.TransactionDate,
		arg.Title,
		arg.ClientRequestID,
		arg.RequestHash,
		arg.ActorUserID,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CategoryID,
		&i.Type,
		&i.Amount,
		&i.TransactionDate,
		&i.Title,
		&i.ClientRequestID,
		&i.RequestHash,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.IsDelete,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActiveTransaction = `-- name: GetActiveTransaction :one
SELECT t.id, t.user_id, t.category_id, t.type, t.amount, t.transaction_date, t.title, t.client_request_id, t.request_hash, t.created_by, t.updated_by, t.is_delete, t.version, t.created_at, t.updated_at, c.name AS category_name
FROM transactions t
JOIN categories c ON c.id = t.category_id AND c.user_id = t.user_id AND c.type = t.type
WHERE t.id = $1 AND t.user_id = $2 AND t.is_delete = FALSE
`

type GetActiveTransactionParams struct {
	ID     int64 `db:"id" json:"id"`
	UserID int64 `db:"user_id" json:"user_id"`
}

type GetActiveTransactionRow struct {
	ID              int64              `db:"id" json:"id"`
	UserID          int64              `db:"user_id" json:"user_id"`
	CategoryID      int64              `db:"category_id" json:"category_id"`
	Type            string             `db:"type" json:"type"`
	Amount          pgtype.Numeric     `db:"amount" json:"amount"`
	TransactionDate pgtype.Date        `db:"transaction_date" json:"transaction_date"`
	Title           string             `db:"title" json:"title"`
	ClientRequestID int64              `db:"client_request_id" json:"client_request_id"`
	RequestHash     string             `db:"request_hash" json:"request_hash"`
	CreatedBy       int64              `db:"created_by" json:"created_by"`
	UpdatedBy       int64              `db:"updated_by" json:"updated_by"`
	IsDelete        bool               `db:"is_delete" json:"is_delete"`
	Version         int32              `db:"version" json:"version"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	CategoryName    string             `db:"category_name" json:"category_name"`
}

func (q *Queries) GetActiveTransaction(ctx context.Context, arg GetActiveTransactionParams) (GetActiveTransactionRow, error) {
	row := q.db.QueryRow(ctx, getActiveTransaction, arg.ID, arg.UserID)
	var i GetActiveTransactionRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CategoryID,
		&i.Type,
		&i.Amount,
		&i.TransactionDate,
		&i.Title,
		&i.ClientRequestID,
		&i.RequestHash,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.IsDelete,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CategoryName,
	)
	return i, err
}

const getDeletedTransaction = `-- name: GetDeletedTransaction :one
SELECT t.id, t.user_id, t.category_id, t.type, t.amount, t.transaction_date, t.title, t.client_request_id, t.request_hash, t.created_by, t.updated_by, t.is_delete, t.version, t.created_at, t.updated_at, c.name AS category_name
FROM transactions t
JOIN categories c ON c.id = t.category_id AND c.user_id = t.user_id AND c.type = t.type
WHERE t.id = $1 AND t.user_id = $2 AND t.is_delete = TRUE
`

type GetDeletedTransactionParams struct {
	ID     int64 `db:"id" json:"id"`
	UserID int64 `db:"user_id" json:"user_id"`
}

type GetDeletedTransactionRow struct {
	ID              int64              `db:"id" json:"id"`
	UserID          int64              `db:"user_id" json:"user_id"`
	CategoryID      int64              `db:"category_id" json:"category_id"`
	Type            string             `db:"type" json:"type"`
	Amount          pgtype.Numeric     `db:"amount" json:"amount"`
	TransactionDate pgtype.Date        `db:"transaction_date" json:"transaction_date"`
	Title           string             `db:"title" json:"title"`
	ClientRequestID int64              `db:"client_request_id" json:"client_request_id"`
	RequestHash     string             `db:"request_hash" json:"request_hash"`
	CreatedBy       int64              `db:"created_by" json:"created_by"`
	UpdatedBy       int64              `db:"updated_by" json:"updated_by"`
	IsDelete        bool               `db:"is_delete" json:"is_delete"`
	Version         int32              `db:"version" json:"version"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	CategoryName    string             `db:"category_name" json:"category_name"`
}

func (q *Queries) GetDeletedTransaction(ctx context.Context, arg GetDeletedTransactionParams) (GetDeletedTransactionRow, error) {
	row := q.db.QueryRow(ctx, getDeletedTransaction, arg.ID, arg.UserID)
	var i GetDeletedTransactionRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CategoryID,
		&i.Type,
		&i.Amount,
		&i.TransactionDate,
		&i.Title,
		&i.ClientRequestID,
		&i.RequestHash,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.IsDelete,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CategoryName,
	)
	return i, err
}

const getReportSummary = `-- name: GetReportSummary :one
SELECT
    COALESCE(SUM(amount) FILTER (WHERE type = 'income'), 0)::numeric(14,2) AS income,
    COALESCE(SUM(amount) FILTER (WHERE type = 'expense'), 0)::numeric(14,2) AS expense
FROM transactions
WHERE user_id = $1
  AND is_delete = FALSE
  AND transaction_date BETWEEN $2 AND $3
`

type GetReportSummaryParams struct {
	UserID    int64       `db:"user_id" json:"user_id"`
	StartDate pgtype.Date `db:"start_date" json:"start_date"`
	EndDate   pgtype.Date `db:"end_date" json:"end_date"`
}

type GetReportSummaryRow struct {
	Income  pgtype.Numeric `db:"income" json:"income"`
	Expense pgtype.Numeric `db:"expense" json:"expense"`
}

func (q *Queries) GetReportSummary(ctx context.Context, arg GetReportSummaryParams) (GetReportSummaryRow, error) {
	row := q.db.QueryRow(ctx, getReportSummary, arg.UserID, arg.StartDate, arg.EndDate)
	var i GetReportSummaryRow
	err := row.Scan(&i.Income, &i.Expense)
	return i, err
}

const getTransactionByRequestIDForUpdate = `-- name: GetTransactionByRequestIDForUpdate :one
SELECT id, user_id, category_id, type, amount, transaction_date, title, client_request_id, request_hash, created_by, updated_by, is_delete, version, created_at, updated_at FROM transactions
WHERE user_id = $1 AND client_request_id = $2
FOR UPDATE
`

type GetTransactionByRequestIDForUpdateParams struct {
	UserID          int64 `db:"user_id" json:"user_id"`
	ClientRequestID int64 `db:"client_request_id" json:"client_request_id"`
}

func (q *Queries) GetTransactionByRequestIDForUpdate(ctx context.Context, arg GetTransactionByRequestIDForUpdateParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, getTransactionByRequestIDForUpdate, arg.UserID, arg.ClientRequestID)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CategoryID,
		&i.Type,
		&i.Amount,
		&i.TransactionDate,
		&i.Title,
		&i.ClientRequestID,
		&i.RequestHash,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.IsDelete,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTransactionStateForUpdate = `-- name: GetTransactionStateForUpdate :one
SELECT id, user_id, category_id, type, amount, transaction_date, title, client_request_id, request_hash, created_by, updated_by, is_delete, version, created_at, updated_at FROM transactions
WHERE id = $1 AND user_id = $2
FOR UPDATE
`

type GetTransactionStateForUpdateParams struct {
	ID     int64 `db:"id" json:"id"`
	UserID int64 `db:"user_id" json:"user_id"`
}

func (q *Queries) GetTransactionStateForUpdate(ctx context.Context, arg GetTransactionStateForUpdateParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, getTransactionStateForUpdate, arg.ID, arg.UserID)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CategoryID,
		&i.Type,
		&i.Amount,
		&i.TransactionDate,
		&i.Title,
		&i.ClientRequestID,
		&i.RequestHash,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.IsDelete,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveTransactions = `-- name: ListActiveTransactions :many
SELECT t.id, t.user_id, t.category_id, t.type, t.amount, t.transaction_date, t.title, t.client_request_id, t.request_hash, t.created_by, t.updated_by, t.is_delete, t.version, t.created_at, t.updated_at, c.name AS category_name
FROM transactions t
JOIN categories c ON c.id = t.category_id AND c.user_id = t.user_id AND c.type = t.type
WHERE t.user_id = $1
  AND t.is_delete = FALSE
  AND t.transaction_date BETWEEN $2 AND $3
  AND ($4::text = '' OR t.type = $4)
  AND (NOT $5::boolean OR t.category_id = $6)
  AND (NOT $7::boolean OR (t.transaction_date, t.created_at, t.id) <
      ($8::date, $9::timestamptz, $10::bigint))
ORDER BY t.transaction_date DESC, t.created_at DESC, t.id DESC
LIMIT $11
`

type ListActiveTransactionsParams struct {
	UserID          int64              `db:"user_id" json:"user_id"`
	StartDate       pgtype.Date        `db:"start_date" json:"start_date"`
	EndDate         pgtype.Date        `db:"end_date" json:"end_date"`
	FilterType      string             `db:"filter_type" json:"filter_type"`
	HasCategory     bool               `db:"has_category" json:"has_category"`
	CategoryID      int64              `db:"category_id" json:"category_id"`
	HasCursor       bool               `db:"has_cursor" json:"has_cursor"`
	CursorDate      pgtype.Date        `db:"cursor_date" json:"cursor_date"`
	CursorCreatedAt pgtype.Timestamptz `db:"cursor_created_at" json:"cursor_created_at"`
	CursorID        int64              `db:"cursor_id" json:"cursor_id"`
	PageSize        int32              `db:"page_size" json:"page_size"`
}

type ListActiveTransactionsRow struct {
	ID              int64              `db:"id" json:"id"`
	UserID          int64              `db:"user_id" json:"user_id"`
	CategoryID      int64              `db:"category_id" json:"category_id"`
	Type            string             `db:"type" json:"type"`
	Amount          pgtype.Numeric     `db:"amount" json:"amount"`
	TransactionDate pgtype.Date        `db:"transaction_date" json:"transaction_date"`
	Title           string             `db:"title" json:"title"`
	ClientRequestID int64              `db:"client_request_id" json:"client_request_id"`
	RequestHash     string             `db:"request_hash" json:"request_hash"`
	CreatedBy       int64              `db:"created_by" json:"created_by"`
	UpdatedBy       int64              `db:"updated_by" json:"updated_by"`
	IsDelete        bool               `db:"is_delete" json:"is_delete"`
	Version         int32              `db:"version" json:"version"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	CategoryName    string             `db:"category_name" json:"category_name"`
}

func (q *Queries) ListActiveTransactions(ctx context.Context, arg ListActiveTransactionsParams) ([]ListActiveTransactionsRow, error) {
	rows, err := q.db.Query(ctx, listActiveTransactions,
		arg.UserID,
		arg.StartDate,
		arg.EndDate,
		arg.FilterType,
		arg.HasCategory,
		arg.CategoryID,
		arg.HasCursor,
		arg.CursorDate,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveTransactionsRow{}
	for rows.Next() {
		var i ListActiveTransactionsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CategoryID,
			&i.Type,
			&i.Amount,
			&i.TransactionDate,
			&i.Title,
			&i.ClientRequestID,
			&i.RequestHash,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.IsDelete,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CategoryName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDailySummaries = `-- name: ListDailySummaries :many
SELECT transaction_date,
       COALESCE(SUM(amount) FILTER (WHERE type = 'income'), 0)::numeric(14,2) AS income,
       COALESCE(SUM(amount) FILTER (WHERE type = 'expense'), 0)::numeric(14,2) AS expense
FROM transactions
WHERE user_id = $1 AND is_delete = FALSE
  AND transaction_date BETWEEN $2 AND $3
  AND (NOT $4::boolean OR transaction_date < $5)
GROUP BY transaction_date
ORDER BY transaction_date DESC
LIMIT $6
`

type ListDailySummariesParams struct {
	UserID     int64       `db:"user_id" json:"user_id"`
	StartDate  pgtype.Date `db:"start_date" json:"start_date"`
	EndDate    pgtype.Date `db:"end_date" json:"end_date"`
	HasCursor  bool        `db:"has_cursor" json:"has_cursor"`
	CursorDate pgtype.Date `db:"cursor_date" json:"cursor_date"`
	PageSize   int32       `db:"page_size" json:"page_size"`
}

type ListDailySummariesRow struct {
	TransactionDate pgtype.Date    `db:"transaction_date" json:"transaction_date"`
	Income          pgtype.Numeric `db:"income" json:"income"`
	Expense         pgtype.Numeric `db:"expense" json:"expense"`
}

func (q *Queries) ListDailySummaries(ctx context.Context, arg ListDailySummariesParams) ([]ListDailySummariesRow, error) {
	rows, err := q.db.Query(ctx, listDailySummaries,
		arg.UserID,
		arg.StartDate,
		arg.EndDate,
		arg.HasCursor,
		arg.CursorDate,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDailySummariesRow{}
	for rows.Next() {
		var i ListDailySummariesRow
		if err := rows.Scan(&i.TransactionDate, &i.Income, &i.Expense); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeletedTransactions = `-- name: ListDeletedTransactions :many
SELECT t.id, t.user_id, t.category_id, t.type, t.amount, t.transaction_date, t.title, t.client_request_id, t.request_hash, t.created_by, t.updated_by, t.is_delete, t.version, t.created_at, t.updated_at, c.name AS category_name
FROM transactions t
JOIN categories c ON c.id = t.category_id AND c.user_id = t.user_id AND c.type = t.type
WHERE t.user_id = $1
  AND t.is_delete = TRUE
  AND t.transaction_date BETWEEN $2 AND $3
  AND ($4::text = '' OR t.type = $4)
  AND (NOT $5::boolean OR t.category_id = $6)
  AND (NOT $7::boolean OR (t.updated_at, t.id) <
      ($8::timestamptz, $9::bigint))
ORDER BY t.updated_at DESC, t.id DESC
LIMIT $10
`

type ListDeletedTransactionsParams struct {
	UserID          int64              `db:"user_id" json:"user_id"`
	StartDate       pgtype.Date        `db:"start_date" json:"start_date"`
	EndDate         pgtype.Date        `db:"end_date" json:"end_date"`
	FilterType      string             `db:"filter_type" json:"filter_type"`
	HasCategory     bool               `db:"has_category" json:"has_category"`
	CategoryID      int64              `db:"category_id" json:"category_id"`
	HasCursor       bool               `db:"has_cursor" json:"has_cursor"`
	CursorUpdatedAt pgtype.Timestamptz `db:"cursor_updated_at" json:"cursor_updated_at"`
	CursorID        int64              `db:"cursor_id" json:"cursor_id"`
	PageSize        int32              `db:"page_size" json:"page_size"`
}

type ListDeletedTransactionsRow struct {
	ID              int64              `db:"id" json:"id"`
	UserID          int64              `db:"user_id" json:"user_id"`
	CategoryID      int64              `db:"category_id" json:"category_id"`
	Type            string             `db:"type" json:"type"`
	Amount          pgtype.Numeric     `db:"amount" json:"amount"`
	TransactionDate pgtype.Date        `db:"transaction_date" json:"transaction_date"`
	Title           string             `db:"title" json:"title"`
	ClientRequestID int64              `db:"client_request_id" json:"client_request_id"`
	RequestHash     string             `db:"request_hash" json:"request_hash"`
	CreatedBy       int64              `db:"created_by" json:"created_by"`
	UpdatedBy       int64              `db:"updated_by" json:"updated_by"`
	IsDelete        bool               `db:"is_delete" json:"is_delete"`
	Version         int32              `db:"version" json:"version"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	CategoryName    string             `db:"category_name" json:"category_name"`
}

func (q *Queries) ListDeletedTransactions(ctx context.Context, arg ListDeletedTransactionsParams) ([]ListDeletedTransactionsRow, error) {
	rows, err := q.db.Query(ctx, listDeletedTransactions,
		arg.UserID,
		arg.StartDate,
		arg.EndDate,
		arg.FilterType,
		arg.HasCategory,
		arg.CategoryID,
		arg.HasCursor,
		arg.CursorUpdatedAt,
		arg.CursorID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDeletedTransactionsRow{}
	for rows.Next() {
		var i ListDeletedTransactionsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CategoryID,
			&i.Type,
			&i.Amount,
			&i.TransactionDate,
			&i.Title,
			&i.ClientRequestID,
			&i.RequestHash,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.IsDelete,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CategoryName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReportCategoryBreakdown = `-- name: ListReportCategoryBreakdown :many
SELECT t.type, t.category_id, c.name,
       SUM(t.amount)::numeric(14,2) AS amount
FROM transactions t
JOIN categories c ON c.id = t.category_id AND c.user_id = t.user_id AND c.type = t.type
WHERE t.user_id = $1
  AND t.is_delete = FALSE
  AND t.transaction_date BETWEEN $2 AND $3
GROUP BY t.type, t.category_id, c.name
ORDER BY t.type ASC, amount DESC, t.category_id ASC
`

type ListReportCategoryBreakdownParams struct {
	UserID    int64       `db:"user_id" json:"user_id"`
	StartDate pgtype.Date `db:"start_date" json:"start_date"`
	EndDate   pgtype.Date `db:"end_date" json:"end_date"`
}

type ListReportCategoryBreakdownRow struct {
	Type       string         `db:"type" json:"type"`
	CategoryID int64          `db:"category_id" json:"category_id"`
	Name       string         `db:"name" json:"name"`
	Amount     pgtype.Numeric `db:"amount" json:"amount"`
}

func (q *Queries) ListReportCategoryBreakdown(ctx context.Context, arg ListReportCategoryBreakdownParams) ([]ListReportCategoryBreakdownRow, error) {
	rows, err := q.db.Query(ctx, listReportCategoryBreakdown, arg.UserID, arg.StartDate, arg.EndDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListReportCategoryBreakdownRow{}
	for rows.Next() {
		var i ListReportCategoryBreakdownRow
		if err := rows.Scan(
			&i.Type,
			&i.CategoryID,
			&i.Name,
			&i.Amount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReportPeriodBreakdown = `-- name: ListReportPeriodBreakdown :many
SELECT date_trunc($1::text, transaction_date)::date AS period_start,
       COALESCE(SUM(amount) FILTER (WHERE type = 'income'), 0)::numeric(14,2) AS income,
       COALESCE(SUM(amount) FILTER (WHERE type = 'expense'), 0)::numeric(14,2) AS expense
FROM transactions
WHERE user_id = $2
  AND is_delete = FALSE
  AND transaction_date BETWEEN $3 AND $4
GROUP BY date_trunc($1::text, transaction_date)::date
ORDER BY period_start ASC
`

type ListReportPeriodBreakdownParams struct {
	GroupBy   string      `db:"group_by" json:"group_by"`
	UserID    int64       `db:"user_id" json:"user_id"`
	StartDate pgtype.Date `db:"start_date" json:"start_date"`
	EndDate   pgtype.Date `db:"end_date" json:"end_date"`
}

type ListReportPeriodBreakdownRow struct {
	PeriodStart pgtype.Date    `db:"period_start" json:"period_start"`
	Income      pgtype.Numeric `db:"income" json:"income"`
	Expense     pgtype.Numeric `db:"expense" json:"expense"`
}

func (q *Queries) ListReportPeriodBreakdown(ctx context.Context, arg ListReportPeriodBreakdownParams) ([]ListReportPeriodBreakdownRow, error) {
	rows, err := q.db.Query(ctx, listReportPeriodBreakdown,
		arg.GroupBy,
		arg.UserID,
		arg.StartDate,
		arg.EndDate,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListReportPeriodBreakdownRow{}
	for rows.Next() {
		var i ListReportPeriodBreakdownRow
		if err := rows.Scan(&i.PeriodStart, &i.Income, &i.Expense); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTopReportCategories = `-- name: ListTopReportCategories :many
WITH totals AS (
    SELECT t.type, t.category_id, c.name,
           SUM(t.amount)::numeric(14,2) AS amount,
           ROW_NUMBER() OVER (PARTITION BY t.type ORDER BY SUM(t.amount) DESC, t.category_id ASC) AS rank
    FROM transactions t
    JOIN categories c ON c.id = t.category_id AND c.user_id = t.user_id AND c.type = t.type
    WHERE t.user_id = $1
      AND t.is_delete = FALSE
      AND t.transaction_date BETWEEN $2 AND $3
    GROUP BY t.type, t.category_id, c.name
)
SELECT type, category_id, name, amount
FROM totals
WHERE rank <= 5
ORDER BY type ASC, amount DESC, category_id ASC
`

type ListTopReportCategoriesParams struct {
	UserID    int64       `db:"user_id" json:"user_id"`
	StartDate pgtype.Date `db:"start_date" json:"start_date"`
	EndDate   pgtype.Date `db:"end_date" json:"end_date"`
}

type ListTopReportCategoriesRow struct {
	Type       string         `db:"type" json:"type"`
	CategoryID int64          `db:"category_id" json:"category_id"`
	Name       string         `db:"name" json:"name"`
	Amount     pgtype.Numeric `db:"amount" json:"amount"`
}

func (q *Queries) ListTopReportCategories(ctx context.Context, arg ListTopReportCategoriesParams) ([]ListTopReportCategoriesRow, error) {
	rows, err := q.db.Query(ctx, listTopReportCategories, arg.UserID, arg.StartDate, arg.EndDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTopReportCategoriesRow{}
	for rows.Next() {
		var i ListTopReportCategoriesRow
		if err := rows.Scan(
			&i.Type,
			&i.CategoryID,
			&i.Name,
			&i.Amount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockScopedCategoryForTransaction = `-- name: LockScopedCategoryForTransaction :one
SELECT id, user_id, type, name, is_delete, version, created_at, updated_at FROM categories
WHERE id = $1 AND user_id = $2
FOR UPDATE
`

type LockScopedCategoryForTransactionParams struct {
	CategoryID int64 `db:"category_id" json:"category_id"`
	UserID     int64 `db:"user_id" json:"user_id"`
}

func (q *Queries) LockScopedCategoryForTransaction(ctx context.Context, arg LockScopedCategoryForTransactionParams) (Category, error) {
	row := q.db.QueryRow(ctx, lockScopedCategoryForTransaction, arg.CategoryID, arg.UserID)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Name,
		&i.IsDelete,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const restoreTransaction = `-- name: RestoreTransaction :one
UPDATE transactions
SET is_delete = FALSE, updated_by = $1,
    version = version + 1, updated_at = CURRENT_TIMESTAMP
WHERE transactions.id = $2 AND transactions.user_id = $3
  AND transactions.version = $4 AND transactions.is_delete = TRUE
  AND EXISTS (SELECT 1 FROM categories WHERE categories.id = transactions.category_id
      AND categories.user_id = transactions.user_id AND categories.type = transactions.type
      AND categories.is_delete = FALSE)
RETURNING id, user_id, category_id, type, amount, transaction_date, title, client_request_id, request_hash, created_by, updated_by, is_delete, version, created_at, updated_at
`

type RestoreTransactionParams struct {
	ActorUserID     int64 `db:"actor_user_id" json:"actor_user_id"`
	ID              int64 `db:"id" json:"id"`
	UserID          int64 `db:"user_id" json:"user_id"`
	ExpectedVersion int32 `db:"expected_version" json:"expected_version"`
}

func (q *Queries) RestoreTransaction(ctx context.Context, arg RestoreTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, restoreTransaction,
		arg.ActorUserID,
		arg.ID,
		arg.UserID,
		arg.ExpectedVersion,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CategoryID,
		&i.Type,
		&i.Amount,
		&i.TransactionDate,
		&i.Title,
		&i.ClientRequestID,
		&i.RequestHash,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.IsDelete,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const softDeleteTransaction = `-- name: SoftDeleteTransaction :one
UPDATE transactions
SET is_delete = TRUE, updated_by = $1,
    version = version + 1, updated_at = CURRENT_TIMESTAMP
WHERE id = $2 AND user_id = $3
  AND version = $4 AND is_delete = FALSE
RETURNING id, user_id, category_id, type, amount, transaction_date, title, client_request_id, request_hash, created_by, updated_by, is_delete, version, created_at, updated_at
`

type SoftDeleteTransactionParams struct {
	ActorUserID     int64 `db:"actor_user_id" json:"actor_user_id"`
	ID              int64 `db:"id" json:"id"`
	UserID          int64 `db:"user_id" json:"user_id"`
	ExpectedVersion int32 `db:"expected_version" json:"expected_version"`
}

func (q *Queries) SoftDeleteTransaction(ctx context.Context, arg SoftDeleteTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, softDeleteTransaction,
		arg.ActorUserID,
		arg.ID,
		arg.UserID,
		arg.ExpectedVersion,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CategoryID,
		&i.Type,
		&i.Amount,
		&i.TransactionDate,
		&i.Title,
		&i.ClientRequestID,
		&i.RequestHash,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.IsDelete,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTransaction = `-- name: UpdateTransaction :one
UPDATE transactions
SET category_id = $1, type = $2, amount = $3,
    transaction_date = $4, title = btrim($5),
    updated_by = $6, version = version + 1, updated_at = CURRENT_TIMESTAMP
WHERE transactions.id = $7 AND transactions.user_id = $8
  AND transactions.version = $9 AND transactions.is_delete = FALSE
  AND EXISTS (SELECT 1 FROM categories WHERE categories.id = $1
      AND categories.user_id = $8 AND categories.type = $2
      AND categories.is_delete = FALSE)
RETURNING id, user_id, category_id, type, amount, transaction_date, title, client_request_id, request_hash, created_by, updated_by, is_delete, version, created_at, updated_at
`

type UpdateTransactionParams struct {
	CategoryID      int64          `db:"category_id" json:"category_id"`
	Type            string         `db:"type" json:"type"`
	Amount          pgtype.Numeric `db:"amount" json:"amount"`
	TransactionDate pgtype.Date    `db:"transaction_date" json:"transaction_date"`
	Title           string         `db:"title" json:"title"`
	ActorUserID     int64          `db:"actor_user_id" json:"actor_user_id"`
	ID              int64          `db:"id" json:"id"`
	UserID          int64          `db:"user_id" json:"user_id"`
	ExpectedVersion int32          `db:"expected_version" json:"expected_version"`
}

func (q *Queries) UpdateTransaction(ctx context.Context, arg UpdateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, updateTransaction,
		arg.CategoryID,
		arg.Type,
		arg.Amount,
		arg.TransactionDate,
		arg.Title,
		arg.ActorUserID,
		arg.ID,
		arg.UserID,
		arg.ExpectedVersion,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CategoryID,
		&i.Type,
		&i.Amount,
		&i.TransactionDate,
		&i.Title,
		&i.ClientRequestID,
		&i.RequestHash,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.IsDelete,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
