// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createInitialAdmin = `-- name: CreateInitialAdmin :one
INSERT INTO users (id, email, password_hash, role, timezone, currency)
SELECT
    $1,
    lower(btrim($2)),
    $3,
    'admin',
    $4,
    'IDR'
WHERE NOT EXISTS (
    SELECT 1
    FROM users
    WHERE role = 'admin'
      AND is_delete = FALSE
)
RETURNING id, email, password_hash, role, timezone, currency, is_delete, version, created_at, updated_at
`

type CreateInitialAdminParams struct {
	ID           pgtype.UUID `db:"id" json:"id"`
	Email        string      `db:"email" json:"email"`
	PasswordHash string      `db:"password_hash" json:"password_hash"`
	Timezone     string      `db:"timezone" json:"timezone"`
}

func (q *Queries) CreateInitialAdmin(ctx context.Context, arg CreateInitialAdminParams) (User, error) {
	row := q.db.QueryRow(ctx, createInitialAdmin,
		arg.ID,
		arg.Email,
		arg.PasswordHash,
		arg.Timezone,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.Timezone,
		&i.Currency,
		&i.IsDelete,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, email, password_hash, timezone, currency)
VALUES (
    $1,
    lower(btrim($2)),
    $3,
    $4,
    $5
)
RETURNING id, email, password_hash, role, timezone, currency, is_delete, version, created_at, updated_at
`

type CreateUserParams struct {
	ID           pgtype.UUID `db:"id" json:"id"`
	Email        string      `db:"email" json:"email"`
	PasswordHash string      `db:"password_hash" json:"password_hash"`
	Timezone     string      `db:"timezone" json:"timezone"`
	Currency     string      `db:"currency" json:"currency"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.Email,
		arg.PasswordHash,
		arg.Timezone,
		arg.Currency,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.Timezone,
		&i.Currency,
		&i.IsDelete,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActiveUserByEmail = `-- name: GetActiveUserByEmail :one
SELECT id, email, password_hash, role, timezone, currency, is_delete, version, created_at, updated_at
FROM users
WHERE email = lower(btrim($1))
  AND is_delete = FALSE
`

func (q *Queries) GetActiveUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getActiveUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.Timezone,
		&i.Currency,
		&i.IsDelete,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActiveUserByID = `-- name: GetActiveUserByID :one
SELECT id, email, password_hash, role, timezone, currency, is_delete, version, created_at, updated_at
FROM users
WHERE id = $1
  AND is_delete = FALSE
`

func (q *Queries) GetActiveUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getActiveUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.Timezone,
		&i.Currency,
		&i.IsDelete,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password_hash, role, timezone, currency, is_delete, version, created_at, updated_at
FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.Timezone,
		&i.Currency,
		&i.IsDelete,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const lockInitialAdminBootstrap = `-- name: LockInitialAdminBootstrap :exec
SELECT pg_advisory_xact_lock(931503)
`

func (q *Queries) LockInitialAdminBootstrap(ctx context.Context) error {
	_, err := q.db.Exec(ctx, lockInitialAdminBootstrap)
	return err
}

const lockUsersForUpdate = `-- name: LockUsersForUpdate :many
SELECT id, email, password_hash, role, timezone, currency, is_delete, version, created_at, updated_at
FROM users
WHERE id = ANY($1::uuid[])
ORDER BY id
FOR UPDATE
`

func (q *Queries) LockUsersForUpdate(ctx context.Context, ids []pgtype.UUID) ([]User, error) {
	rows, err := q.db.Query(ctx, lockUsersForUpdate, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.PasswordHash,
			&i.Role,
			&i.Timezone,
			&i.Currency,
			&i.IsDelete,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restoreUser = `-- name: RestoreUser :one
UPDATE users
SET is_delete = FALSE,
    version = version + 1,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
  AND version = $2
  AND is_delete = TRUE
RETURNING id, email, password_hash, role, timezone, currency, is_delete, version, created_at, updated_at
`

type RestoreUserParams struct {
	ID              pgtype.UUID `db:"id" json:"id"`
	ExpectedVersion int32       `db:"expected_version" json:"expected_version"`
}

func (q *Queries) RestoreUser(ctx context.Context, arg RestoreUserParams) (User, error) {
	row := q.db.QueryRow(ctx, restoreUser, arg.ID, arg.ExpectedVersion)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.Timezone,
		&i.Currency,
		&i.IsDelete,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const softDeleteUser = `-- name: SoftDeleteUser :one
UPDATE users
SET is_delete = TRUE,
    version = version + 1,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
  AND version = $2
  AND is_delete = FALSE
RETURNING id, email, password_hash, role, timezone, currency, is_delete, version, created_at, updated_at
`

type SoftDeleteUserParams struct {
	ID              pgtype.UUID `db:"id" json:"id"`
	ExpectedVersion int32       `db:"expected_version" json:"expected_version"`
}

func (q *Queries) SoftDeleteUser(ctx context.Context, arg SoftDeleteUserParams) (User, error) {
	row := q.db.QueryRow(ctx, softDeleteUser, arg.ID, arg.ExpectedVersion)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.Timezone,
		&i.Currency,
		&i.IsDelete,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE users
SET email = lower(btrim($1)),
    timezone = $2,
    currency = $3,
    version = version + 1,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $4
  AND version = $5
  AND is_delete = FALSE
RETURNING id, email, password_hash, role, timezone, currency, is_delete, version, created_at, updated_at
`

type UpdateUserProfileParams struct {
	Email           string      `db:"email" json:"email"`
	Timezone        string      `db:"timezone" json:"timezone"`
	Currency        string      `db:"currency" json:"currency"`
	ID              pgtype.UUID `db:"id" json:"id"`
	ExpectedVersion int32       `db:"expected_version" json:"expected_version"`
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserProfile,
		arg.Email,
		arg.Timezone,
		arg.Currency,
		arg.ID,
		arg.ExpectedVersion,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.Timezone,
		&i.Currency,
		&i.IsDelete,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
